/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AccountNumberDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5533003612186746284L;
    private String description;
    private String externalCode1;
    private String externalCode2;
    private String number;
    private TypeEnum type;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("externalCode1")
    public String getExternalCode1 ( ) { 
        return this.externalCode1;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("externalCode1")
    public void setExternalCode1 (String value) { 
        this.externalCode1 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("externalCode2")
    public String getExternalCode2 ( ) { 
        return this.externalCode2;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("externalCode2")
    public void setExternalCode2 (String value) { 
        this.externalCode2 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("number")
    public String getNumber ( ) { 
        return this.number;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("number")
    public void setNumber (String value) { 
        this.number = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public TypeEnum getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (TypeEnum value) { 
        this.type = value;
    }
 
}
 