/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class AccountNumberDtoBuilder {
    //the instance to build
    private AccountNumberDto accountNumberDto;

    /**
     * Default constructor to initialize the instance
     */
    public AccountNumberDtoBuilder() {
        accountNumberDto = new AccountNumberDto();
    }

    public AccountNumberDtoBuilder description(String description) {
        accountNumberDto.setDescription(description);
        return this;
    }

    public AccountNumberDtoBuilder externalCode1(String externalCode1) {
        accountNumberDto.setExternalCode1(externalCode1);
        return this;
    }

    public AccountNumberDtoBuilder externalCode2(String externalCode2) {
        accountNumberDto.setExternalCode2(externalCode2);
        return this;
    }

    public AccountNumberDtoBuilder number(String number) {
        accountNumberDto.setNumber(number);
        return this;
    }

    public AccountNumberDtoBuilder type(TypeEnum type) {
        accountNumberDto.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AccountNumberDto build() {
        return accountNumberDto;
    }
}