/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class AccountNumberTypeDescriptionDtoBuilder {
    //the instance to build
    private AccountNumberTypeDescriptionDto accountNumberTypeDescriptionDto;

    /**
     * Default constructor to initialize the instance
     */
    public AccountNumberTypeDescriptionDtoBuilder() {
        accountNumberTypeDescriptionDto = new AccountNumberTypeDescriptionDto();
    }

    public AccountNumberTypeDescriptionDtoBuilder description(String description) {
        accountNumberTypeDescriptionDto.setDescription(description);
        return this;
    }

    public AccountNumberTypeDescriptionDtoBuilder number(String number) {
        accountNumberTypeDescriptionDto.setNumber(number);
        return this;
    }

    public AccountNumberTypeDescriptionDtoBuilder type(String type) {
        accountNumberTypeDescriptionDto.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AccountNumberTypeDescriptionDto build() {
        return accountNumberTypeDescriptionDto;
    }
}