/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class AccountQueryParametersBuilder {
    //the instance to build
    private AccountQueryParameters accountQueryParameters;

    /**
     * Default constructor to initialize the instance
     */
    public AccountQueryParametersBuilder() {
        accountQueryParameters = new AccountQueryParameters();
    }

    public AccountQueryParametersBuilder greaterThanValue(String greaterThanValue) {
        accountQueryParameters.setGreaterThanValue(greaterThanValue);
        return this;
    }

    public AccountQueryParametersBuilder lastModifiedDateTime(String lastModifiedDateTime) {
        accountQueryParameters.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public AccountQueryParametersBuilder lastModifiedDateTimeCondition(String lastModifiedDateTimeCondition) {
        accountQueryParameters.setLastModifiedDateTimeCondition(lastModifiedDateTimeCondition);
        return this;
    }

    public AccountQueryParametersBuilder numberToRead(Integer numberToRead) {
        accountQueryParameters.setNumberToRead(numberToRead);
        return this;
    }

    public AccountQueryParametersBuilder orderBy(String orderBy) {
        accountQueryParameters.setOrderBy(orderBy);
        return this;
    }

    public AccountQueryParametersBuilder skipRecords(Integer skipRecords) {
        accountQueryParameters.setSkipRecords(skipRecords);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AccountQueryParameters build() {
        return accountQueryParameters;
    }
}