/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class AttachmentDtoBuilder {
    //the instance to build
    private AttachmentDto attachmentDto;

    /**
     * Default constructor to initialize the instance
     */
    public AttachmentDtoBuilder() {
        attachmentDto = new AttachmentDto();
    }

    public AttachmentDtoBuilder id(String id) {
        attachmentDto.setId(id);
        return this;
    }

    public AttachmentDtoBuilder name(String name) {
        attachmentDto.setName(name);
        return this;
    }

    public AttachmentDtoBuilder revision(Integer revision) {
        attachmentDto.setRevision(revision);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AttachmentDto build() {
        return attachmentDto;
    }
}