/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class BranchQueryParametersBuilder {
    //the instance to build
    private BranchQueryParameters branchQueryParameters;

    /**
     * Default constructor to initialize the instance
     */
    public BranchQueryParametersBuilder() {
        branchQueryParameters = new BranchQueryParameters();
    }

    public BranchQueryParametersBuilder greaterThanValue(String greaterThanValue) {
        branchQueryParameters.setGreaterThanValue(greaterThanValue);
        return this;
    }

    public BranchQueryParametersBuilder lastModifiedDateTime(String lastModifiedDateTime) {
        branchQueryParameters.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public BranchQueryParametersBuilder lastModifiedDateTimeCondition(String lastModifiedDateTimeCondition) {
        branchQueryParameters.setLastModifiedDateTimeCondition(lastModifiedDateTimeCondition);
        return this;
    }

    public BranchQueryParametersBuilder numberToRead(Integer numberToRead) {
        branchQueryParameters.setNumberToRead(numberToRead);
        return this;
    }

    public BranchQueryParametersBuilder orderBy(String orderBy) {
        branchQueryParameters.setOrderBy(orderBy);
        return this;
    }

    public BranchQueryParametersBuilder skipRecords(Integer skipRecords) {
        branchQueryParameters.setSkipRecords(skipRecords);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BranchQueryParameters build() {
        return branchQueryParameters;
    }
}