/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum ChargeBearerEnum {
    PAYER, //TODO: Write general description for this element
    BENEFICIARY, //TODO: Write general description for this element
    SHARED, //TODO: Write general description for this element
    SERVICELEVEL; //TODO: Write general description for this element

    private static TreeMap<String, ChargeBearerEnum> valueMap = new TreeMap<String, ChargeBearerEnum>();
    private String value;

    static {
        PAYER.value = "Payer";
        BENEFICIARY.value = "Beneficiary";
        SHARED.value = "Shared";
        SERVICELEVEL.value = "ServiceLevel";

        valueMap.put("Payer", PAYER);
        valueMap.put("Beneficiary", BENEFICIARY);
        valueMap.put("Shared", SHARED);
        valueMap.put("ServiceLevel", SERVICELEVEL);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ChargeBearerEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ChargeBearerEnum values to list of string values
     * @param toConvert The list of ChargeBearerEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<ChargeBearerEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (ChargeBearerEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 