/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class ConsolBranchDtoBuilder {
    //the instance to build
    private ConsolBranchDto consolBranchDto;

    /**
     * Default constructor to initialize the instance
     */
    public ConsolBranchDtoBuilder() {
        consolBranchDto = new ConsolBranchDto();
    }

    public ConsolBranchDtoBuilder name(String name) {
        consolBranchDto.setName(name);
        return this;
    }

    public ConsolBranchDtoBuilder number(String number) {
        consolBranchDto.setNumber(number);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ConsolBranchDto build() {
        return consolBranchDto;
    }
}