/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class CreateShipmentActionDtoBuilder {
    //the instance to build
    private CreateShipmentActionDto createShipmentActionDto;

    /**
     * Default constructor to initialize the instance
     */
    public CreateShipmentActionDtoBuilder() {
        createShipmentActionDto = new CreateShipmentActionDto();
    }

    public CreateShipmentActionDtoBuilder orderType(String orderType) {
        createShipmentActionDto.setOrderType(orderType);
        return this;
    }

    public CreateShipmentActionDtoBuilder returnShipmentDto(Boolean returnShipmentDto) {
        createShipmentActionDto.setReturnShipmentDto(returnShipmentDto);
        return this;
    }

    public CreateShipmentActionDtoBuilder shipmentDate(Date shipmentDate) {
        createShipmentActionDto.setShipmentDate(shipmentDate);
        return this;
    }

    public CreateShipmentActionDtoBuilder shipmentWarehouse(String shipmentWarehouse) {
        createShipmentActionDto.setShipmentWarehouse(shipmentWarehouse);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateShipmentActionDto build() {
        return createShipmentActionDto;
    }
}