/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class CreditNoteLineDtoBuilder {
    //the instance to build
    private CreditNoteLineDto creditNoteLineDto;

    /**
     * Default constructor to initialize the instance
     */
    public CreditNoteLineDtoBuilder() {
        creditNoteLineDto = new CreditNoteLineDto();
    }

    public CreditNoteLineDtoBuilder account(AccountNumberDto account) {
        creditNoteLineDto.setAccount(account);
        return this;
    }

    public CreditNoteLineDtoBuilder amount(Double amount) {
        creditNoteLineDto.setAmount(amount);
        return this;
    }

    public CreditNoteLineDtoBuilder amountInCurrency(Double amountInCurrency) {
        creditNoteLineDto.setAmountInCurrency(amountInCurrency);
        return this;
    }

    public CreditNoteLineDtoBuilder attachments(List<AttachmentDto> attachments) {
        creditNoteLineDto.setAttachments(attachments);
        return this;
    }

    public CreditNoteLineDtoBuilder deferralCode(String deferralCode) {
        creditNoteLineDto.setDeferralCode(deferralCode);
        return this;
    }

    public CreditNoteLineDtoBuilder deferralSchedule(Integer deferralSchedule) {
        creditNoteLineDto.setDeferralSchedule(deferralSchedule);
        return this;
    }

    public CreditNoteLineDtoBuilder description(String description) {
        creditNoteLineDto.setDescription(description);
        return this;
    }

    public CreditNoteLineDtoBuilder discountAmount(Double discountAmount) {
        creditNoteLineDto.setDiscountAmount(discountAmount);
        return this;
    }

    public CreditNoteLineDtoBuilder discountAmountInCurrency(Double discountAmountInCurrency) {
        creditNoteLineDto.setDiscountAmountInCurrency(discountAmountInCurrency);
        return this;
    }

    public CreditNoteLineDtoBuilder discountCode(String discountCode) {
        creditNoteLineDto.setDiscountCode(discountCode);
        return this;
    }

    public CreditNoteLineDtoBuilder discountPercent(Double discountPercent) {
        creditNoteLineDto.setDiscountPercent(discountPercent);
        return this;
    }

    public CreditNoteLineDtoBuilder inventoryNumber(String inventoryNumber) {
        creditNoteLineDto.setInventoryNumber(inventoryNumber);
        return this;
    }

    public CreditNoteLineDtoBuilder lineNumber(Integer lineNumber) {
        creditNoteLineDto.setLineNumber(lineNumber);
        return this;
    }

    public CreditNoteLineDtoBuilder manualAmount(Double manualAmount) {
        creditNoteLineDto.setManualAmount(manualAmount);
        return this;
    }

    public CreditNoteLineDtoBuilder manualAmountInCurrency(Double manualAmountInCurrency) {
        creditNoteLineDto.setManualAmountInCurrency(manualAmountInCurrency);
        return this;
    }

    public CreditNoteLineDtoBuilder manualDiscount(Boolean manualDiscount) {
        creditNoteLineDto.setManualDiscount(manualDiscount);
        return this;
    }

    public CreditNoteLineDtoBuilder note(String note) {
        creditNoteLineDto.setNote(note);
        return this;
    }

    public CreditNoteLineDtoBuilder quantity(Double quantity) {
        creditNoteLineDto.setQuantity(quantity);
        return this;
    }

    public CreditNoteLineDtoBuilder salesperson(String salesperson) {
        creditNoteLineDto.setSalesperson(salesperson);
        return this;
    }

    public CreditNoteLineDtoBuilder subaccount(SubAccountDto subaccount) {
        creditNoteLineDto.setSubaccount(subaccount);
        return this;
    }

    public CreditNoteLineDtoBuilder unitPrice(Double unitPrice) {
        creditNoteLineDto.setUnitPrice(unitPrice);
        return this;
    }

    public CreditNoteLineDtoBuilder unitPriceInCurrency(Double unitPriceInCurrency) {
        creditNoteLineDto.setUnitPriceInCurrency(unitPriceInCurrency);
        return this;
    }

    public CreditNoteLineDtoBuilder uom(String uom) {
        creditNoteLineDto.setUom(uom);
        return this;
    }

    public CreditNoteLineDtoBuilder vatCode(VatCodeDto vatCode) {
        creditNoteLineDto.setVatCode(vatCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreditNoteLineDto build() {
        return creditNoteLineDto;
    }
}