/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum CreditVerificationEnum {
    DISABLED, //TODO: Write general description for this element
    DAYSPASTDUE, //TODO: Write general description for this element
    CREDITLIMIT, //TODO: Write general description for this element
    LIMITANDDAYSPASTDUE; //TODO: Write general description for this element

    private static TreeMap<String, CreditVerificationEnum> valueMap = new TreeMap<String, CreditVerificationEnum>();
    private String value;

    static {
        DISABLED.value = "Disabled";
        DAYSPASTDUE.value = "DaysPastDue";
        CREDITLIMIT.value = "CreditLimit";
        LIMITANDDAYSPASTDUE.value = "LimitAndDaysPastDue";

        valueMap.put("Disabled", DISABLED);
        valueMap.put("DaysPastDue", DAYSPASTDUE);
        valueMap.put("CreditLimit", CREDITLIMIT);
        valueMap.put("LimitAndDaysPastDue", LIMITANDDAYSPASTDUE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static CreditVerificationEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CreditVerificationEnum values to list of string values
     * @param toConvert The list of CreditVerificationEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<CreditVerificationEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (CreditVerificationEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 