/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CustomerDescriptionDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4995980474670620293L;
    private Integer internalId;
    private String name;
    private String number;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("internalId")
    public Integer getInternalId ( ) { 
        return this.internalId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("internalId")
    public void setInternalId (Integer value) { 
        this.internalId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("number")
    public String getNumber ( ) { 
        return this.number;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("number")
    public void setNumber (String value) { 
        this.number = value;
    }
 
}
 