/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class CustomerUpdateDtoBuilder {
    //the instance to build
    private CustomerUpdateDto customerUpdateDto;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerUpdateDtoBuilder() {
        customerUpdateDto = new CustomerUpdateDto();
    }

    public CustomerUpdateDtoBuilder acceptAutoInvoices(DtoValueBoolean acceptAutoInvoices) {
        customerUpdateDto.setAcceptAutoInvoices(acceptAutoInvoices);
        return this;
    }

    public CustomerUpdateDtoBuilder accountReference(DtoValueString accountReference) {
        customerUpdateDto.setAccountReference(accountReference);
        return this;
    }

    public CustomerUpdateDtoBuilder corporateId(DtoValueString corporateId) {
        customerUpdateDto.setCorporateId(corporateId);
        return this;
    }

    public CustomerUpdateDtoBuilder creditDaysPastDue(DtoValueNullableInt32 creditDaysPastDue) {
        customerUpdateDto.setCreditDaysPastDue(creditDaysPastDue);
        return this;
    }

    public CustomerUpdateDtoBuilder creditLimit(DtoValueDecimal creditLimit) {
        customerUpdateDto.setCreditLimit(creditLimit);
        return this;
    }

    public CustomerUpdateDtoBuilder creditTermsId(DtoValueString creditTermsId) {
        customerUpdateDto.setCreditTermsId(creditTermsId);
        return this;
    }

    public CustomerUpdateDtoBuilder creditVerification(DtoValueCreditRule creditVerification) {
        customerUpdateDto.setCreditVerification(creditVerification);
        return this;
    }

    public CustomerUpdateDtoBuilder currencyId(DtoValueString currencyId) {
        customerUpdateDto.setCurrencyId(currencyId);
        return this;
    }

    public CustomerUpdateDtoBuilder customerClassId(DtoValueString customerClassId) {
        customerUpdateDto.setCustomerClassId(customerClassId);
        return this;
    }

    public CustomerUpdateDtoBuilder deliveryAddress(DtoValueAddressUpdateDto deliveryAddress) {
        customerUpdateDto.setDeliveryAddress(deliveryAddress);
        return this;
    }

    public CustomerUpdateDtoBuilder deliveryContact(DtoValueContactInfoUpdateDto deliveryContact) {
        customerUpdateDto.setDeliveryContact(deliveryContact);
        return this;
    }

    public CustomerUpdateDtoBuilder invoiceAddress(DtoValueAddressUpdateDto invoiceAddress) {
        customerUpdateDto.setInvoiceAddress(invoiceAddress);
        return this;
    }

    public CustomerUpdateDtoBuilder invoiceContact(DtoValueContactInfoUpdateDto invoiceContact) {
        customerUpdateDto.setInvoiceContact(invoiceContact);
        return this;
    }

    public CustomerUpdateDtoBuilder mainAddress(DtoValueAddressUpdateDto mainAddress) {
        customerUpdateDto.setMainAddress(mainAddress);
        return this;
    }

    public CustomerUpdateDtoBuilder mainContact(DtoValueContactInfoUpdateDto mainContact) {
        customerUpdateDto.setMainContact(mainContact);
        return this;
    }

    public CustomerUpdateDtoBuilder name(DtoValueString name) {
        customerUpdateDto.setName(name);
        return this;
    }

    public CustomerUpdateDtoBuilder number(DtoValueString number) {
        customerUpdateDto.setNumber(number);
        return this;
    }

    public CustomerUpdateDtoBuilder overrideWithClassValues(Boolean overrideWithClassValues) {
        customerUpdateDto.setOverrideWithClassValues(overrideWithClassValues);
        return this;
    }

    public CustomerUpdateDtoBuilder parentRecordNumber(DtoValueString parentRecordNumber) {
        customerUpdateDto.setParentRecordNumber(parentRecordNumber);
        return this;
    }

    public CustomerUpdateDtoBuilder printInvoices(DtoValueBoolean printInvoices) {
        customerUpdateDto.setPrintInvoices(printInvoices);
        return this;
    }

    public CustomerUpdateDtoBuilder printMultiCurrencyStatements(DtoValueBoolean printMultiCurrencyStatements) {
        customerUpdateDto.setPrintMultiCurrencyStatements(printMultiCurrencyStatements);
        return this;
    }

    public CustomerUpdateDtoBuilder printStatements(DtoValueBoolean printStatements) {
        customerUpdateDto.setPrintStatements(printStatements);
        return this;
    }

    public CustomerUpdateDtoBuilder sendInvoicesByEmail(DtoValueBoolean sendInvoicesByEmail) {
        customerUpdateDto.setSendInvoicesByEmail(sendInvoicesByEmail);
        return this;
    }

    public CustomerUpdateDtoBuilder sendStatementsByEmail(DtoValueBoolean sendStatementsByEmail) {
        customerUpdateDto.setSendStatementsByEmail(sendStatementsByEmail);
        return this;
    }

    public CustomerUpdateDtoBuilder statementType(DtoValueStatementTypes statementType) {
        customerUpdateDto.setStatementType(statementType);
        return this;
    }

    public CustomerUpdateDtoBuilder status(DtoValueCustomerStatus status) {
        customerUpdateDto.setStatus(status);
        return this;
    }

    public CustomerUpdateDtoBuilder vatRegistrationId(DtoValueString vatRegistrationId) {
        customerUpdateDto.setVatRegistrationId(vatRegistrationId);
        return this;
    }

    public CustomerUpdateDtoBuilder vatZoneId(DtoValueString vatZoneId) {
        customerUpdateDto.setVatZoneId(vatZoneId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerUpdateDto build() {
        return customerUpdateDto;
    }
}