/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class CustomerBalanceQueryParametersBuilder {
    //the instance to build
    private CustomerBalanceQueryParameters customerBalanceQueryParameters;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerBalanceQueryParametersBuilder() {
        customerBalanceQueryParameters = new CustomerBalanceQueryParameters();
    }

    public CustomerBalanceQueryParametersBuilder greaterThanValue(String greaterThanValue) {
        customerBalanceQueryParameters.setGreaterThanValue(greaterThanValue);
        return this;
    }

    public CustomerBalanceQueryParametersBuilder lastModifiedDateTime(String lastModifiedDateTime) {
        customerBalanceQueryParameters.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public CustomerBalanceQueryParametersBuilder lastModifiedDateTimeCondition(String lastModifiedDateTimeCondition) {
        customerBalanceQueryParameters.setLastModifiedDateTimeCondition(lastModifiedDateTimeCondition);
        return this;
    }

    public CustomerBalanceQueryParametersBuilder numberToRead(Integer numberToRead) {
        customerBalanceQueryParameters.setNumberToRead(numberToRead);
        return this;
    }

    public CustomerBalanceQueryParametersBuilder orderBy(String orderBy) {
        customerBalanceQueryParameters.setOrderBy(orderBy);
        return this;
    }

    public CustomerBalanceQueryParametersBuilder skipRecords(Integer skipRecords) {
        customerBalanceQueryParameters.setSkipRecords(skipRecords);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerBalanceQueryParameters build() {
        return customerBalanceQueryParameters;
    }
}