/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class CustomerDtoBuilder {
    //the instance to build
    private CustomerDto customerDto;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerDtoBuilder() {
        customerDto = new CustomerDto();
    }

    public CustomerDtoBuilder acceptAutoInvoices(Boolean acceptAutoInvoices) {
        customerDto.setAcceptAutoInvoices(acceptAutoInvoices);
        return this;
    }

    public CustomerDtoBuilder accountReference(String accountReference) {
        customerDto.setAccountReference(accountReference);
        return this;
    }

    public CustomerDtoBuilder corporateId(String corporateId) {
        customerDto.setCorporateId(corporateId);
        return this;
    }

    public CustomerDtoBuilder createdDateTime(Date createdDateTime) {
        customerDto.setCreatedDateTime(createdDateTime);
        return this;
    }

    public CustomerDtoBuilder creditDaysPastDue(Integer creditDaysPastDue) {
        customerDto.setCreditDaysPastDue(creditDaysPastDue);
        return this;
    }

    public CustomerDtoBuilder creditLimit(Double creditLimit) {
        customerDto.setCreditLimit(creditLimit);
        return this;
    }

    public CustomerDtoBuilder creditTerms(CreditTermsDto creditTerms) {
        customerDto.setCreditTerms(creditTerms);
        return this;
    }

    public CustomerDtoBuilder creditVerification(CreditVerificationEnum creditVerification) {
        customerDto.setCreditVerification(creditVerification);
        return this;
    }

    public CustomerDtoBuilder currencyId(String currencyId) {
        customerDto.setCurrencyId(currencyId);
        return this;
    }

    public CustomerDtoBuilder customerClass(ClassDescriptionDto customerClass) {
        customerDto.setCustomerClass(customerClass);
        return this;
    }

    public CustomerDtoBuilder deliveryAddress(AddressDto deliveryAddress) {
        customerDto.setDeliveryAddress(deliveryAddress);
        return this;
    }

    public CustomerDtoBuilder deliveryContact(ContactInfoDto deliveryContact) {
        customerDto.setDeliveryContact(deliveryContact);
        return this;
    }

    public CustomerDtoBuilder internalId(Integer internalId) {
        customerDto.setInternalId(internalId);
        return this;
    }

    public CustomerDtoBuilder invoiceAddress(AddressDto invoiceAddress) {
        customerDto.setInvoiceAddress(invoiceAddress);
        return this;
    }

    public CustomerDtoBuilder invoiceContact(ContactInfoDto invoiceContact) {
        customerDto.setInvoiceContact(invoiceContact);
        return this;
    }

    public CustomerDtoBuilder lastModifiedDateTime(Date lastModifiedDateTime) {
        customerDto.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public CustomerDtoBuilder location(LocationDto location) {
        customerDto.setLocation(location);
        return this;
    }

    public CustomerDtoBuilder mainAddress(AddressDto mainAddress) {
        customerDto.setMainAddress(mainAddress);
        return this;
    }

    public CustomerDtoBuilder mainContact(ContactInfoDto mainContact) {
        customerDto.setMainContact(mainContact);
        return this;
    }

    public CustomerDtoBuilder name(String name) {
        customerDto.setName(name);
        return this;
    }

    public CustomerDtoBuilder number(String number) {
        customerDto.setNumber(number);
        return this;
    }

    public CustomerDtoBuilder parentRecord(ParentRecordDto parentRecord) {
        customerDto.setParentRecord(parentRecord);
        return this;
    }

    public CustomerDtoBuilder printInvoices(Boolean printInvoices) {
        customerDto.setPrintInvoices(printInvoices);
        return this;
    }

    public CustomerDtoBuilder printMultiCurrencyStatements(Boolean printMultiCurrencyStatements) {
        customerDto.setPrintMultiCurrencyStatements(printMultiCurrencyStatements);
        return this;
    }

    public CustomerDtoBuilder printStatements(Boolean printStatements) {
        customerDto.setPrintStatements(printStatements);
        return this;
    }

    public CustomerDtoBuilder sendInvoicesByEmail(Boolean sendInvoicesByEmail) {
        customerDto.setSendInvoicesByEmail(sendInvoicesByEmail);
        return this;
    }

    public CustomerDtoBuilder sendStatementsByEmail(Boolean sendStatementsByEmail) {
        customerDto.setSendStatementsByEmail(sendStatementsByEmail);
        return this;
    }

    public CustomerDtoBuilder statementType(StatementTypeEnum statementType) {
        customerDto.setStatementType(statementType);
        return this;
    }

    public CustomerDtoBuilder status(Status91Enum status) {
        customerDto.setStatus(status);
        return this;
    }

    public CustomerDtoBuilder vatRegistrationId(String vatRegistrationId) {
        customerDto.setVatRegistrationId(vatRegistrationId);
        return this;
    }

    public CustomerDtoBuilder vatZone(VatZoneDto vatZone) {
        customerDto.setVatZone(vatZone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomerDto build() {
        return customerDto;
    }
}