/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CustomerInvoiceUpdateDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4659874463077182009L;
    private DtoValueDateTime cashDiscountDate;
    private DtoValueString creditTermsId;
    private DtoValueString currencyId;
    private DtoValueString customerNumber;
    private DtoValueString customerRefNumber;
    private DtoValueDateTime documentDate;
    private DtoValueDateTime documentDueDate;
    private DtoValueDecimal exchangeRate;
    private DtoValueString externalReference;
    private DtoValueString financialPeriod;
    private DtoValueBoolean hold;
    private List<CustomerInvoiceLinesUpdateDto> invoiceLines;
    private DtoValueString invoiceText;
    private DtoValueString locationId;
    private DtoValueString note;
    private DtoValueString paymentMethodId;
    private DtoValueString postPeriod;
    private DtoValueString referenceNumber;
    private DtoValueNullableInt32 salesPersonID;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cashDiscountDate")
    public DtoValueDateTime getCashDiscountDate ( ) { 
        return this.cashDiscountDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cashDiscountDate")
    public void setCashDiscountDate (DtoValueDateTime value) { 
        this.cashDiscountDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("creditTermsId")
    public DtoValueString getCreditTermsId ( ) { 
        return this.creditTermsId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("creditTermsId")
    public void setCreditTermsId (DtoValueString value) { 
        this.creditTermsId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("currencyId")
    public DtoValueString getCurrencyId ( ) { 
        return this.currencyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("currencyId")
    public void setCurrencyId (DtoValueString value) { 
        this.currencyId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customerNumber")
    public DtoValueString getCustomerNumber ( ) { 
        return this.customerNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customerNumber")
    public void setCustomerNumber (DtoValueString value) { 
        this.customerNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customerRefNumber")
    public DtoValueString getCustomerRefNumber ( ) { 
        return this.customerRefNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customerRefNumber")
    public void setCustomerRefNumber (DtoValueString value) { 
        this.customerRefNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("documentDate")
    public DtoValueDateTime getDocumentDate ( ) { 
        return this.documentDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("documentDate")
    public void setDocumentDate (DtoValueDateTime value) { 
        this.documentDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("documentDueDate")
    public DtoValueDateTime getDocumentDueDate ( ) { 
        return this.documentDueDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("documentDueDate")
    public void setDocumentDueDate (DtoValueDateTime value) { 
        this.documentDueDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exchangeRate")
    public DtoValueDecimal getExchangeRate ( ) { 
        return this.exchangeRate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exchangeRate")
    public void setExchangeRate (DtoValueDecimal value) { 
        this.exchangeRate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("externalReference")
    public DtoValueString getExternalReference ( ) { 
        return this.externalReference;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("externalReference")
    public void setExternalReference (DtoValueString value) { 
        this.externalReference = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("financialPeriod")
    public DtoValueString getFinancialPeriod ( ) { 
        return this.financialPeriod;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("financialPeriod")
    public void setFinancialPeriod (DtoValueString value) { 
        this.financialPeriod = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hold")
    public DtoValueBoolean getHold ( ) { 
        return this.hold;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hold")
    public void setHold (DtoValueBoolean value) { 
        this.hold = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("invoiceLines")
    public List<CustomerInvoiceLinesUpdateDto> getInvoiceLines ( ) { 
        return this.invoiceLines;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("invoiceLines")
    public void setInvoiceLines (List<CustomerInvoiceLinesUpdateDto> value) { 
        this.invoiceLines = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("invoiceText")
    public DtoValueString getInvoiceText ( ) { 
        return this.invoiceText;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("invoiceText")
    public void setInvoiceText (DtoValueString value) { 
        this.invoiceText = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("locationId")
    public DtoValueString getLocationId ( ) { 
        return this.locationId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("locationId")
    public void setLocationId (DtoValueString value) { 
        this.locationId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("note")
    public DtoValueString getNote ( ) { 
        return this.note;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("note")
    public void setNote (DtoValueString value) { 
        this.note = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentMethodId")
    public DtoValueString getPaymentMethodId ( ) { 
        return this.paymentMethodId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentMethodId")
    public void setPaymentMethodId (DtoValueString value) { 
        this.paymentMethodId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("postPeriod")
    public DtoValueString getPostPeriod ( ) { 
        return this.postPeriod;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("postPeriod")
    public void setPostPeriod (DtoValueString value) { 
        this.postPeriod = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("referenceNumber")
    public DtoValueString getReferenceNumber ( ) { 
        return this.referenceNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("referenceNumber")
    public void setReferenceNumber (DtoValueString value) { 
        this.referenceNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("salesPersonID")
    public DtoValueNullableInt32 getSalesPersonID ( ) { 
        return this.salesPersonID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("salesPersonID")
    public void setSalesPersonID (DtoValueNullableInt32 value) { 
        this.salesPersonID = value;
    }
 
}
 