/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class DtoSegmentBuilder {
    //the instance to build
    private DtoSegment dtoSegment;

    /**
     * Default constructor to initialize the instance
     */
    public DtoSegmentBuilder() {
        dtoSegment = new DtoSegment();
    }

    public DtoSegmentBuilder description(String description) {
        dtoSegment.setDescription(description);
        return this;
    }

    public DtoSegmentBuilder lastModified(Date lastModified) {
        dtoSegment.setLastModified(lastModified);
        return this;
    }

    public DtoSegmentBuilder length(Integer length) {
        dtoSegment.setLength(length);
        return this;
    }

    public DtoSegmentBuilder publicId(String publicId) {
        dtoSegment.setPublicId(publicId);
        return this;
    }

    public DtoSegmentBuilder segmentId(Integer segmentId) {
        dtoSegment.setSegmentId(segmentId);
        return this;
    }

    public DtoSegmentBuilder segmentValues(List<DtoSegmentValue> segmentValues) {
        dtoSegment.setSegmentValues(segmentValues);
        return this;
    }

    public DtoSegmentBuilder timeStamp(String timeStamp) {
        dtoSegment.setTimeStamp(timeStamp);
        return this;
    }

    public DtoSegmentBuilder validate(Boolean validate) {
        dtoSegment.setValidate(validate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DtoSegment build() {
        return dtoSegment;
    }
}