/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class DtoSegmentUpdateBuilder {
    //the instance to build
    private DtoSegmentUpdate dtoSegmentUpdate;

    /**
     * Default constructor to initialize the instance
     */
    public DtoSegmentUpdateBuilder() {
        dtoSegmentUpdate = new DtoSegmentUpdate();
    }

    public DtoSegmentUpdateBuilder description(DtoValueString description) {
        dtoSegmentUpdate.setDescription(description);
        return this;
    }

    public DtoSegmentUpdateBuilder dimensionId(String dimensionId) {
        dtoSegmentUpdate.setDimensionId(dimensionId);
        return this;
    }

    public DtoSegmentUpdateBuilder publicId(DtoValueNullableGuid publicId) {
        dtoSegmentUpdate.setPublicId(publicId);
        return this;
    }

    public DtoSegmentUpdateBuilder segementId(Integer segementId) {
        dtoSegmentUpdate.setSegementId(segementId);
        return this;
    }

    public DtoSegmentUpdateBuilder segmentValues(List<DtoSegmentValueUpdate> segmentValues) {
        dtoSegmentUpdate.setSegmentValues(segmentValues);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DtoSegmentUpdate build() {
        return dtoSegmentUpdate;
    }
}