/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class DtoValueSalesOrderContactUpdateDtoBuilder {
    //the instance to build
    private DtoValueSalesOrderContactUpdateDto dtoValueSalesOrderContactUpdateDto;

    /**
     * Default constructor to initialize the instance
     */
    public DtoValueSalesOrderContactUpdateDtoBuilder() {
        dtoValueSalesOrderContactUpdateDto = new DtoValueSalesOrderContactUpdateDto();
    }

    public DtoValueSalesOrderContactUpdateDtoBuilder value(SalesOrderContactUpdateDto value) {
        dtoValueSalesOrderContactUpdateDto.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DtoValueSalesOrderContactUpdateDto build() {
        return dtoValueSalesOrderContactUpdateDto;
    }
}