/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class DtoValueInventoryTypeBuilder {
    //the instance to build
    private DtoValueInventoryType dtoValueInventoryType;

    /**
     * Default constructor to initialize the instance
     */
    public DtoValueInventoryTypeBuilder() {
        dtoValueInventoryType = new DtoValueInventoryType();
    }

    public DtoValueInventoryTypeBuilder value(Value156Enum value) {
        dtoValueInventoryType.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DtoValueInventoryType build() {
        return dtoValueInventoryType;
    }
}