/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DtoValueContactMethods 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4878661982793289073L;
    private Value51Enum value;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("value")
    public Value51Enum getValue ( ) { 
        return this.value;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("value")
    public void setValue (Value51Enum value) { 
        this.value = value;
    }
 
}
 