/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class DtoValueNullableDecimalBuilder {
    //the instance to build
    private DtoValueNullableDecimal dtoValueNullableDecimal;

    /**
     * Default constructor to initialize the instance
     */
    public DtoValueNullableDecimalBuilder() {
        dtoValueNullableDecimal = new DtoValueNullableDecimal();
    }

    public DtoValueNullableDecimalBuilder value(Double value) {
        dtoValueNullableDecimal.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DtoValueNullableDecimal build() {
        return dtoValueNullableDecimal;
    }
}