/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class DtoValueNullableDateTimeBuilder {
    //the instance to build
    private DtoValueNullableDateTime dtoValueNullableDateTime;

    /**
     * Default constructor to initialize the instance
     */
    public DtoValueNullableDateTimeBuilder() {
        dtoValueNullableDateTime = new DtoValueNullableDateTime();
    }

    public DtoValueNullableDateTimeBuilder value(Date value) {
        dtoValueNullableDateTime.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DtoValueNullableDateTime build() {
        return dtoValueNullableDateTime;
    }
}