/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class DtoValueNullableBooleanBuilder {
    //the instance to build
    private DtoValueNullableBoolean dtoValueNullableBoolean;

    /**
     * Default constructor to initialize the instance
     */
    public DtoValueNullableBooleanBuilder() {
        dtoValueNullableBoolean = new DtoValueNullableBoolean();
    }

    public DtoValueNullableBooleanBuilder value(Boolean value) {
        dtoValueNullableBoolean.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DtoValueNullableBoolean build() {
        return dtoValueNullableBoolean;
    }
}