/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class DtoValueCustomerStatusBuilder {
    //the instance to build
    private DtoValueCustomerStatus dtoValueCustomerStatus;

    /**
     * Default constructor to initialize the instance
     */
    public DtoValueCustomerStatusBuilder() {
        dtoValueCustomerStatus = new DtoValueCustomerStatus();
    }

    public DtoValueCustomerStatusBuilder value(Value98Enum value) {
        dtoValueCustomerStatus.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DtoValueCustomerStatus build() {
        return dtoValueCustomerStatus;
    }
}