/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class EmployeeContactDtoBuilder {
    //the instance to build
    private EmployeeContactDto employeeContactDto;

    /**
     * Default constructor to initialize the instance
     */
    public EmployeeContactDtoBuilder() {
        employeeContactDto = new EmployeeContactDto();
    }

    public EmployeeContactDtoBuilder attention(String attention) {
        employeeContactDto.setAttention(attention);
        return this;
    }

    public EmployeeContactDtoBuilder contactId(Integer contactId) {
        employeeContactDto.setContactId(contactId);
        return this;
    }

    public EmployeeContactDtoBuilder email(String email) {
        employeeContactDto.setEmail(email);
        return this;
    }

    public EmployeeContactDtoBuilder employeeContact(String employeeContact) {
        employeeContactDto.setEmployeeContact(employeeContact);
        return this;
    }

    public EmployeeContactDtoBuilder fax(String fax) {
        employeeContactDto.setFax(fax);
        return this;
    }

    public EmployeeContactDtoBuilder firstName(String firstName) {
        employeeContactDto.setFirstName(firstName);
        return this;
    }

    public EmployeeContactDtoBuilder lastName(String lastName) {
        employeeContactDto.setLastName(lastName);
        return this;
    }

    public EmployeeContactDtoBuilder midName(String midName) {
        employeeContactDto.setMidName(midName);
        return this;
    }

    public EmployeeContactDtoBuilder name(String name) {
        employeeContactDto.setName(name);
        return this;
    }

    public EmployeeContactDtoBuilder phone1(String phone1) {
        employeeContactDto.setPhone1(phone1);
        return this;
    }

    public EmployeeContactDtoBuilder phone2(String phone2) {
        employeeContactDto.setPhone2(phone2);
        return this;
    }

    public EmployeeContactDtoBuilder phone3(String phone3) {
        employeeContactDto.setPhone3(phone3);
        return this;
    }

    public EmployeeContactDtoBuilder title(TitleEnum title) {
        employeeContactDto.setTitle(title);
        return this;
    }

    public EmployeeContactDtoBuilder web(String web) {
        employeeContactDto.setWeb(web);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EmployeeContactDto build() {
        return employeeContactDto;
    }
}