/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FinancialPeriodQueryParameters 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5370562814235950597L;
    private String greaterThanValue;
    private Integer numberToRead;
    private String orderBy;
    private Integer skipRecords;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("greaterThanValue")
    public String getGreaterThanValue ( ) { 
        return this.greaterThanValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("greaterThanValue")
    public void setGreaterThanValue (String value) { 
        this.greaterThanValue = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("numberToRead")
    public Integer getNumberToRead ( ) { 
        return this.numberToRead;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("numberToRead")
    public void setNumberToRead (Integer value) { 
        this.numberToRead = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("orderBy")
    public String getOrderBy ( ) { 
        return this.orderBy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("orderBy")
    public void setOrderBy (String value) { 
        this.orderBy = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("skipRecords")
    public Integer getSkipRecords ( ) { 
        return this.skipRecords;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("skipRecords")
    public void setSkipRecords (Integer value) { 
        this.skipRecords = value;
    }
 
}
 