/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class GeneralLedgerBalanceQueryParametersBuilder {
    //the instance to build
    private GeneralLedgerBalanceQueryParameters generalLedgerBalanceQueryParameters;

    /**
     * Default constructor to initialize the instance
     */
    public GeneralLedgerBalanceQueryParametersBuilder() {
        generalLedgerBalanceQueryParameters = new GeneralLedgerBalanceQueryParameters();
    }

    public GeneralLedgerBalanceQueryParametersBuilder accountId(String accountId) {
        generalLedgerBalanceQueryParameters.setAccountId(accountId);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder balanceType(BalanceTypeEnum balanceType) {
        generalLedgerBalanceQueryParameters.setBalanceType(balanceType);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder greaterThanValue(String greaterThanValue) {
        generalLedgerBalanceQueryParameters.setGreaterThanValue(greaterThanValue);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder lastModifiedDateTime(String lastModifiedDateTime) {
        generalLedgerBalanceQueryParameters.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder lastModifiedDateTimeCondition(String lastModifiedDateTimeCondition) {
        generalLedgerBalanceQueryParameters.setLastModifiedDateTimeCondition(lastModifiedDateTimeCondition);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder numberToRead(Integer numberToRead) {
        generalLedgerBalanceQueryParameters.setNumberToRead(numberToRead);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder orderBy(String orderBy) {
        generalLedgerBalanceQueryParameters.setOrderBy(orderBy);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder periodId(String periodId) {
        generalLedgerBalanceQueryParameters.setPeriodId(periodId);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder periodIdCondition(String periodIdCondition) {
        generalLedgerBalanceQueryParameters.setPeriodIdCondition(periodIdCondition);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder skipRecords(Integer skipRecords) {
        generalLedgerBalanceQueryParameters.setSkipRecords(skipRecords);
        return this;
    }

    public GeneralLedgerBalanceQueryParametersBuilder yearClosed(Integer yearClosed) {
        generalLedgerBalanceQueryParameters.setYearClosed(yearClosed);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GeneralLedgerBalanceQueryParameters build() {
        return generalLedgerBalanceQueryParameters;
    }
}