/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class InventoryReceiptLineUpdateDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5597244764093648056L;
    private DtoValueString description;
    private DtoValueNullableDecimal extCost;
    private DtoValueString inventoryNumber;
    private DtoValueInt32 lineNumber;
    private DtoValueString locationId;
    private OperationEnum operation;
    private DtoValueNullableDecimal quantity;
    private DtoValueString reasonCode;
    private DtoValueNullableDecimal unitCost;
    private DtoValueString uom;
    private DtoValueString warehouseId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public DtoValueString getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (DtoValueString value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("extCost")
    public DtoValueNullableDecimal getExtCost ( ) { 
        return this.extCost;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("extCost")
    public void setExtCost (DtoValueNullableDecimal value) { 
        this.extCost = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("inventoryNumber")
    public DtoValueString getInventoryNumber ( ) { 
        return this.inventoryNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("inventoryNumber")
    public void setInventoryNumber (DtoValueString value) { 
        this.inventoryNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lineNumber")
    public DtoValueInt32 getLineNumber ( ) { 
        return this.lineNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lineNumber")
    public void setLineNumber (DtoValueInt32 value) { 
        this.lineNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("locationId")
    public DtoValueString getLocationId ( ) { 
        return this.locationId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("locationId")
    public void setLocationId (DtoValueString value) { 
        this.locationId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("operation")
    public OperationEnum getOperation ( ) { 
        return this.operation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("operation")
    public void setOperation (OperationEnum value) { 
        this.operation = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("quantity")
    public DtoValueNullableDecimal getQuantity ( ) { 
        return this.quantity;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("quantity")
    public void setQuantity (DtoValueNullableDecimal value) { 
        this.quantity = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("reasonCode")
    public DtoValueString getReasonCode ( ) { 
        return this.reasonCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("reasonCode")
    public void setReasonCode (DtoValueString value) { 
        this.reasonCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("unitCost")
    public DtoValueNullableDecimal getUnitCost ( ) { 
        return this.unitCost;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("unitCost")
    public void setUnitCost (DtoValueNullableDecimal value) { 
        this.unitCost = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("uom")
    public DtoValueString getUom ( ) { 
        return this.uom;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("uom")
    public void setUom (DtoValueString value) { 
        this.uom = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("warehouseId")
    public DtoValueString getWarehouseId ( ) { 
        return this.warehouseId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("warehouseId")
    public void setWarehouseId (DtoValueString value) { 
        this.warehouseId = value;
    }
 
}
 