/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class InventoryIdNameDtoBuilder {
    //the instance to build
    private InventoryIdNameDto inventoryIdNameDto;

    /**
     * Default constructor to initialize the instance
     */
    public InventoryIdNameDtoBuilder() {
        inventoryIdNameDto = new InventoryIdNameDto();
    }

    public InventoryIdNameDtoBuilder id(Integer id) {
        inventoryIdNameDto.setId(id);
        return this;
    }

    public InventoryIdNameDtoBuilder name(String name) {
        inventoryIdNameDto.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InventoryIdNameDto build() {
        return inventoryIdNameDto;
    }
}