/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class InventoryIssueDtoBuilder {
    //the instance to build
    private InventoryIssueDto inventoryIssueDto;

    /**
     * Default constructor to initialize the instance
     */
    public InventoryIssueDtoBuilder() {
        inventoryIssueDto = new InventoryIssueDto();
    }

    /**
     * The reference number of the batch generated for the receipt. Click the number to open the Journal Transactions (GL.30.10.00) form and view the details of the transactions.
     */
    public InventoryIssueDtoBuilder batchNumber(String batchNumber) {
        inventoryIssueDto.setBatchNumber(batchNumber);
        return this;
    }

    /**
     * The manually entered summary amount for all specified inventory items. Control Amount is available only if the Validate Document Totals on Entry option is selected on the Inventory Preferences form. If the Control Amount and Total Amount values do not match, the system generates a warning message and the issue cannot be saved.
     */
    public InventoryIssueDtoBuilder controlAmount(Double controlAmount) {
        inventoryIssueDto.setControlAmount(controlAmount);
        return this;
    }

    /**
     * The manually entered quantity of inventory items. Control Qty. is available only if the Validate Document Totals on Entry option is selected on the Inventory Preferences form. If the Control Qty. and Total Qty.values do not match, the system generates a warning message and the issue cannot be saved.
     */
    public InventoryIssueDtoBuilder controlQuantity(Double controlQuantity) {
        inventoryIssueDto.setControlQuantity(controlQuantity);
        return this;
    }

    /**
     * The date when the receipt was created. All transactions included in this document will have this transaction date.
     */
    public InventoryIssueDtoBuilder date(Date date) {
        inventoryIssueDto.setDate(date);
        return this;
    }

    /**
     * A brief description of the inventory issue or its transactions.
     */
    public InventoryIssueDtoBuilder description(String description) {
        inventoryIssueDto.setDescription(description);
        return this;
    }

    /**
     * The external reference number of the inventory issue document (for example, the vendor’s reference code).
     */
    public InventoryIssueDtoBuilder externalReference(String externalReference) {
        inventoryIssueDto.setExternalReference(externalReference);
        return this;
    }

    /**
     * A check box that you select to give the receipt the On Hold status. Clear the check box to save the receipt with the Balanced status.
     */
    public InventoryIssueDtoBuilder hold(Boolean hold) {
        inventoryIssueDto.setHold(hold);
        return this;
    }

    /**
     * The inventory issue lines
     */
    public InventoryIssueDtoBuilder issueLines(List<InventoryIssueLineDto> issueLines) {
        inventoryIssueDto.setIssueLines(issueLines);
        return this;
    }

    /**
     * The date when the document was last modified.
     */
    public InventoryIssueDtoBuilder lastModifiedDateTime(Date lastModifiedDateTime) {
        inventoryIssueDto.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    /**
     * The financial period to which the transactions recorded in the document should be posted.
     */
    public InventoryIssueDtoBuilder postPeriod(String postPeriod) {
        inventoryIssueDto.setPostPeriod(postPeriod);
        return this;
    }

    /**
     * The unique reference number of the receipt, which the system automatically assigns according to the numbering sequence selected for receipts on the Inventory Preferences IN.10.10.00) form.
     */
    public InventoryIssueDtoBuilder referenceNumber(String referenceNumber) {
        inventoryIssueDto.setReferenceNumber(referenceNumber);
        return this;
    }

    /**
     * The current status of the receipt. The following options are available: 
     *             On Hold:The receipt/issue is a draft and can be edited. Receipts with this status cannot be released.
     *             Balanced: The receipt/issue data has been validated by the system and the receipt can be released. It also can be modified or deleted, but changes can be saved only if the receipt is balanced.
     *             Released: The receipt/issue has been released and cannot be edited or deleted.
     */
    public InventoryIssueDtoBuilder status(Status161Enum status) {
        inventoryIssueDto.setStatus(status);
        return this;
    }

    /**
     * The total amount, calculated as a sum of amounts for all inventory issue operations included in this issue document.
     */
    public InventoryIssueDtoBuilder totalAmount(Double totalAmount) {
        inventoryIssueDto.setTotalAmount(totalAmount);
        return this;
    }

    /**
     * The total quantity of inventory items, which the system calculates automatically, for the document.
     */
    public InventoryIssueDtoBuilder totalQuantity(Double totalQuantity) {
        inventoryIssueDto.setTotalQuantity(totalQuantity);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InventoryIssueDto build() {
        return inventoryIssueDto;
    }
}