/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class InventoryIssueLineDtoBuilder {
    //the instance to build
    private InventoryIssueLineDto inventoryIssueLineDto;

    /**
     * Default constructor to initialize the instance
     */
    public InventoryIssueLineDtoBuilder() {
        inventoryIssueLineDto = new InventoryIssueLineDto();
    }

    public InventoryIssueLineDtoBuilder description(String description) {
        inventoryIssueLineDto.setDescription(description);
        return this;
    }

    public InventoryIssueLineDtoBuilder extCost(Double extCost) {
        inventoryIssueLineDto.setExtCost(extCost);
        return this;
    }

    public InventoryIssueLineDtoBuilder extPrice(Double extPrice) {
        inventoryIssueLineDto.setExtPrice(extPrice);
        return this;
    }

    public InventoryIssueLineDtoBuilder inventoryItem(InventoryNumberDescriptionDto inventoryItem) {
        inventoryIssueLineDto.setInventoryItem(inventoryItem);
        return this;
    }

    public InventoryIssueLineDtoBuilder lineNumber(Integer lineNumber) {
        inventoryIssueLineDto.setLineNumber(lineNumber);
        return this;
    }

    public InventoryIssueLineDtoBuilder location(LocationDto location) {
        inventoryIssueLineDto.setLocation(location);
        return this;
    }

    public InventoryIssueLineDtoBuilder quantity(Double quantity) {
        inventoryIssueLineDto.setQuantity(quantity);
        return this;
    }

    public InventoryIssueLineDtoBuilder reasonCode(ReasonCodeDto reasonCode) {
        inventoryIssueLineDto.setReasonCode(reasonCode);
        return this;
    }

    public InventoryIssueLineDtoBuilder transactionType(TransactionTypeEnum transactionType) {
        inventoryIssueLineDto.setTransactionType(transactionType);
        return this;
    }

    public InventoryIssueLineDtoBuilder unitCost(Double unitCost) {
        inventoryIssueLineDto.setUnitCost(unitCost);
        return this;
    }

    public InventoryIssueLineDtoBuilder unitPrice(Double unitPrice) {
        inventoryIssueLineDto.setUnitPrice(unitPrice);
        return this;
    }

    public InventoryIssueLineDtoBuilder uom(String uom) {
        inventoryIssueLineDto.setUom(uom);
        return this;
    }

    public InventoryIssueLineDtoBuilder warehouse(WarehouseIdDescriptionDto warehouse) {
        inventoryIssueLineDto.setWarehouse(warehouse);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InventoryIssueLineDto build() {
        return inventoryIssueLineDto;
    }
}