/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class InventoryAdjustmentUpdateDtoBuilder {
    //the instance to build
    private InventoryAdjustmentUpdateDto inventoryAdjustmentUpdateDto;

    /**
     * Default constructor to initialize the instance
     */
    public InventoryAdjustmentUpdateDtoBuilder() {
        inventoryAdjustmentUpdateDto = new InventoryAdjustmentUpdateDto();
    }

    /**
     * The inventory adjustment lines
     */
    public InventoryAdjustmentUpdateDtoBuilder adjustmentLines(List<InventoryAdjustmentLineUpdateDto> adjustmentLines) {
        inventoryAdjustmentUpdateDto.setAdjustmentLines(adjustmentLines);
        return this;
    }

    /**
     * The manually entered summary cost for all specified inventory adjustment items.
     */
    public InventoryAdjustmentUpdateDtoBuilder controlCost(DtoValueNullableDecimal controlCost) {
        inventoryAdjustmentUpdateDto.setControlCost(controlCost);
        return this;
    }

    /**
     * The manually entered quantity of inventory items. Control Qty. is available only if the Validate Document Totals on Entry option is selected on the Inventory Preferences form. If the Control Qty. and Total Qty.values do not match, the system generates a warning message and the issue cannot be saved.
     */
    public InventoryAdjustmentUpdateDtoBuilder controlQuantity(DtoValueNullableDecimal controlQuantity) {
        inventoryAdjustmentUpdateDto.setControlQuantity(controlQuantity);
        return this;
    }

    /**
     * The date when the receipt was created. All transactions included in this document will have this transaction date.
     */
    public InventoryAdjustmentUpdateDtoBuilder date(DtoValueNullableDateTime date) {
        inventoryAdjustmentUpdateDto.setDate(date);
        return this;
    }

    /**
     * A brief description of the inventory issue or its transactions.
     */
    public InventoryAdjustmentUpdateDtoBuilder description(DtoValueString description) {
        inventoryAdjustmentUpdateDto.setDescription(description);
        return this;
    }

    /**
     * The external reference number of the inventory issue document (for example, the vendor’s reference code).
     */
    public InventoryAdjustmentUpdateDtoBuilder externalReference(DtoValueString externalReference) {
        inventoryAdjustmentUpdateDto.setExternalReference(externalReference);
        return this;
    }

    /**
     * A check box that you select to give the receipt the On Hold status. Clear the check box to save the receipt with the Balanced status.
     */
    public InventoryAdjustmentUpdateDtoBuilder hold(DtoValueNullableBoolean hold) {
        inventoryAdjustmentUpdateDto.setHold(hold);
        return this;
    }

    /**
     * The financial period to which the transactions recorded in the document should be posted.
     */
    public InventoryAdjustmentUpdateDtoBuilder postPeriod(DtoValueString postPeriod) {
        inventoryAdjustmentUpdateDto.setPostPeriod(postPeriod);
        return this;
    }

    /**
     * The unique reference number of the receipt, which the system automatically assigns according to the numbering sequence selected for receipts on the Inventory Preferences IN.10.10.00) form.
     */
    public InventoryAdjustmentUpdateDtoBuilder referenceNumber(DtoValueString referenceNumber) {
        inventoryAdjustmentUpdateDto.setReferenceNumber(referenceNumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InventoryAdjustmentUpdateDto build() {
        return inventoryAdjustmentUpdateDto;
    }
}