/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class InventoryUpdateDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5528797526470718384L;
    private DtoValueNullableDecimal defaultPrice;
    private DtoValueString description;
    private DtoValueString inventoryNumber;
    private DtoValueString itemClass;
    private DtoValueString postingClass;
    private DtoValueInventoryStatus status;
    private DtoValueInventoryType type;
    private DtoValueString vatCode;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("defaultPrice")
    public DtoValueNullableDecimal getDefaultPrice ( ) { 
        return this.defaultPrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("defaultPrice")
    public void setDefaultPrice (DtoValueNullableDecimal value) { 
        this.defaultPrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public DtoValueString getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (DtoValueString value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("inventoryNumber")
    public DtoValueString getInventoryNumber ( ) { 
        return this.inventoryNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("inventoryNumber")
    public void setInventoryNumber (DtoValueString value) { 
        this.inventoryNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("itemClass")
    public DtoValueString getItemClass ( ) { 
        return this.itemClass;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("itemClass")
    public void setItemClass (DtoValueString value) { 
        this.itemClass = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("postingClass")
    public DtoValueString getPostingClass ( ) { 
        return this.postingClass;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("postingClass")
    public void setPostingClass (DtoValueString value) { 
        this.postingClass = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("status")
    public DtoValueInventoryStatus getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("status")
    public void setStatus (DtoValueInventoryStatus value) { 
        this.status = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public DtoValueInventoryType getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (DtoValueInventoryType value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatCode")
    public DtoValueString getVatCode ( ) { 
        return this.vatCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatCode")
    public void setVatCode (DtoValueString value) { 
        this.vatCode = value;
    }
 
}
 