/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class JournalTransactionLineDtoBuilder {
    //the instance to build
    private JournalTransactionLineDto journalTransactionLineDto;

    /**
     * Default constructor to initialize the instance
     */
    public JournalTransactionLineDtoBuilder() {
        journalTransactionLineDto = new JournalTransactionLineDto();
    }

    public JournalTransactionLineDtoBuilder accountNumber(String accountNumber) {
        journalTransactionLineDto.setAccountNumber(accountNumber);
        return this;
    }

    public JournalTransactionLineDtoBuilder creditAmount(Double creditAmount) {
        journalTransactionLineDto.setCreditAmount(creditAmount);
        return this;
    }

    public JournalTransactionLineDtoBuilder creditAmountInCurrency(Double creditAmountInCurrency) {
        journalTransactionLineDto.setCreditAmountInCurrency(creditAmountInCurrency);
        return this;
    }

    public JournalTransactionLineDtoBuilder debitAmount(Double debitAmount) {
        journalTransactionLineDto.setDebitAmount(debitAmount);
        return this;
    }

    public JournalTransactionLineDtoBuilder debitAmountInCurrency(Double debitAmountInCurrency) {
        journalTransactionLineDto.setDebitAmountInCurrency(debitAmountInCurrency);
        return this;
    }

    public JournalTransactionLineDtoBuilder description(String description) {
        journalTransactionLineDto.setDescription(description);
        return this;
    }

    public JournalTransactionLineDtoBuilder lineNumber(Integer lineNumber) {
        journalTransactionLineDto.setLineNumber(lineNumber);
        return this;
    }

    public JournalTransactionLineDtoBuilder referenceNumber(String referenceNumber) {
        journalTransactionLineDto.setReferenceNumber(referenceNumber);
        return this;
    }

    public JournalTransactionLineDtoBuilder subaccount(SubAccountDto subaccount) {
        journalTransactionLineDto.setSubaccount(subaccount);
        return this;
    }

    public JournalTransactionLineDtoBuilder transactionDescription(String transactionDescription) {
        journalTransactionLineDto.setTransactionDescription(transactionDescription);
        return this;
    }

    public JournalTransactionLineDtoBuilder vat(VatDto vat) {
        journalTransactionLineDto.setVat(vat);
        return this;
    }

    public JournalTransactionLineDtoBuilder vatCode(VatCodeDto vatCode) {
        journalTransactionLineDto.setVatCode(vatCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public JournalTransactionLineDto build() {
        return journalTransactionLineDto;
    }
}