/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class LedgerDtoBuilder {
    //the instance to build
    private LedgerDto ledgerDto;

    /**
     * Default constructor to initialize the instance
     */
    public LedgerDtoBuilder() {
        ledgerDto = new LedgerDto();
    }

    public LedgerDtoBuilder balanceType(BalanceTypeEnum balanceType) {
        ledgerDto.setBalanceType(balanceType);
        return this;
    }

    public LedgerDtoBuilder branchAccounting(Boolean branchAccounting) {
        ledgerDto.setBranchAccounting(branchAccounting);
        return this;
    }

    public LedgerDtoBuilder consolBranch(ConsolBranchDto consolBranch) {
        ledgerDto.setConsolBranch(consolBranch);
        return this;
    }

    public LedgerDtoBuilder consolidationSource(Boolean consolidationSource) {
        ledgerDto.setConsolidationSource(consolidationSource);
        return this;
    }

    public LedgerDtoBuilder currencyId(String currencyId) {
        ledgerDto.setCurrencyId(currencyId);
        return this;
    }

    public LedgerDtoBuilder description(String description) {
        ledgerDto.setDescription(description);
        return this;
    }

    public LedgerDtoBuilder internalId(Integer internalId) {
        ledgerDto.setInternalId(internalId);
        return this;
    }

    public LedgerDtoBuilder lastModifiedDateTime(Date lastModifiedDateTime) {
        ledgerDto.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public LedgerDtoBuilder number(String number) {
        ledgerDto.setNumber(number);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LedgerDto build() {
        return ledgerDto;
    }
}