/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PaymentMethodDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5687729233912645824L;
    private Boolean active;
    private String description;
    private List<PaymentMethodDetailDto> details;
    private MeansOfPaymentEnum meansOfPayment;
    private String paymentMethodID;
    private Boolean useInAP;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("active")
    public Boolean getActive ( ) { 
        return this.active;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("active")
    public void setActive (Boolean value) { 
        this.active = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("details")
    public List<PaymentMethodDetailDto> getDetails ( ) { 
        return this.details;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("details")
    public void setDetails (List<PaymentMethodDetailDto> value) { 
        this.details = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("meansOfPayment")
    public MeansOfPaymentEnum getMeansOfPayment ( ) { 
        return this.meansOfPayment;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("meansOfPayment")
    public void setMeansOfPayment (MeansOfPaymentEnum value) { 
        this.meansOfPayment = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentMethodID")
    public String getPaymentMethodID ( ) { 
        return this.paymentMethodID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentMethodID")
    public void setPaymentMethodID (String value) { 
        this.paymentMethodID = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("useInAP")
    public Boolean getUseInAP ( ) { 
        return this.useInAP;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("useInAP")
    public void setUseInAP (Boolean value) { 
        this.useInAP = value;
    }
 
}
 