/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class PaymentQueryParametersBuilder {
    //the instance to build
    private PaymentQueryParameters paymentQueryParameters;

    /**
     * Default constructor to initialize the instance
     */
    public PaymentQueryParametersBuilder() {
        paymentQueryParameters = new PaymentQueryParameters();
    }

    public PaymentQueryParametersBuilder greaterThanValue(String greaterThanValue) {
        paymentQueryParameters.setGreaterThanValue(greaterThanValue);
        return this;
    }

    public PaymentQueryParametersBuilder lastModifiedDateTime(String lastModifiedDateTime) {
        paymentQueryParameters.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public PaymentQueryParametersBuilder lastModifiedDateTimeCondition(String lastModifiedDateTimeCondition) {
        paymentQueryParameters.setLastModifiedDateTimeCondition(lastModifiedDateTimeCondition);
        return this;
    }

    public PaymentQueryParametersBuilder numberToRead(Integer numberToRead) {
        paymentQueryParameters.setNumberToRead(numberToRead);
        return this;
    }

    public PaymentQueryParametersBuilder orderBy(String orderBy) {
        paymentQueryParameters.setOrderBy(orderBy);
        return this;
    }

    public PaymentQueryParametersBuilder skipRecords(Integer skipRecords) {
        paymentQueryParameters.setSkipRecords(skipRecords);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PaymentQueryParameters build() {
        return paymentQueryParameters;
    }
}