/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class ProjectTaskDtoBuilder {
    //the instance to build
    private ProjectTaskDto projectTaskDto;

    /**
     * Default constructor to initialize the instance
     */
    public ProjectTaskDtoBuilder() {
        projectTaskDto = new ProjectTaskDto();
    }

    public ProjectTaskDtoBuilder description(String description) {
        projectTaskDto.setDescription(description);
        return this;
    }

    public ProjectTaskDtoBuilder id(String id) {
        projectTaskDto.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ProjectTaskDto build() {
        return projectTaskDto;
    }
}