/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PurchaseOrderDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5704772763447316276L;
    private BranchNumberDto branch;
    private Double controlTotal;
    private String currency;
    private Date date;
    private String description;
    private List<DiscountDetailDto> discountDetails;
    private Boolean dontEmail;
    private Boolean dontPrint;
    private Boolean emailed;
    private String fobPoint;
    private Boolean hold;
    private Date lastModifiedDateTime;
    private List<PurchaseOrderLineDto> lines;
    private Double lineTotal;
    private LocationIdNameDto location;
    private Double openBalance;
    private Double openQuantity;
    private String orderNbr;
    private Double orderTotal;
    private OrderTypeEnum orderType;
    private UserDescriptionDto owner;
    private String paymentRefNbr;
    private Boolean printed;
    private Date promisedOn;
    private PurchaseOrderAddressDto remitAddress;
    private PurchaseOrderContactDto remitContact;
    private String requisitionRefNbr;
    private String salesOrderNbr;
    private String salesOrderType;
    private PurchaseOrderAddressDto shippingAddress;
    private PurchaseOrderContactDto shippingContact;
    private ShippingDestinationTypeEnum shippingDestinationType;
    private LocationIdNameDto shippingLocation;
    private BAccountDescriptionDto shipTo;
    private String shipVia;
    private Status238Enum status;
    private SupplierDescriptionDto supplier;
    private String supplierRef;
    private VatZoneDto supplierVatZone;
    private List<TaxDetailDto> taxDetails;
    private Double taxTotal;
    private CreditTermsDto terms;
    private Double vatExemptTotal;
    private Integer workgroupID;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("branch")
    public BranchNumberDto getBranch ( ) { 
        return this.branch;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("branch")
    public void setBranch (BranchNumberDto value) { 
        this.branch = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("controlTotal")
    public Double getControlTotal ( ) { 
        return this.controlTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("controlTotal")
    public void setControlTotal (Double value) { 
        this.controlTotal = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("currency")
    public String getCurrency ( ) { 
        return this.currency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("currency")
    public void setCurrency (String value) { 
        this.currency = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date")
    public Date getDate ( ) { 
        return this.date;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date")
    public void setDate (Date value) { 
        this.date = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("discountDetails")
    public List<DiscountDetailDto> getDiscountDetails ( ) { 
        return this.discountDetails;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("discountDetails")
    public void setDiscountDetails (List<DiscountDetailDto> value) { 
        this.discountDetails = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("dontEmail")
    public Boolean getDontEmail ( ) { 
        return this.dontEmail;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("dontEmail")
    public void setDontEmail (Boolean value) { 
        this.dontEmail = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("dontPrint")
    public Boolean getDontPrint ( ) { 
        return this.dontPrint;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("dontPrint")
    public void setDontPrint (Boolean value) { 
        this.dontPrint = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("emailed")
    public Boolean getEmailed ( ) { 
        return this.emailed;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("emailed")
    public void setEmailed (Boolean value) { 
        this.emailed = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fobPoint")
    public String getFobPoint ( ) { 
        return this.fobPoint;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fobPoint")
    public void setFobPoint (String value) { 
        this.fobPoint = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hold")
    public Boolean getHold ( ) { 
        return this.hold;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hold")
    public void setHold (Boolean value) { 
        this.hold = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lastModifiedDateTime")
    public Date getLastModifiedDateTime ( ) { 
        return this.lastModifiedDateTime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lastModifiedDateTime")
    public void setLastModifiedDateTime (Date value) { 
        this.lastModifiedDateTime = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lines")
    public List<PurchaseOrderLineDto> getLines ( ) { 
        return this.lines;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lines")
    public void setLines (List<PurchaseOrderLineDto> value) { 
        this.lines = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lineTotal")
    public Double getLineTotal ( ) { 
        return this.lineTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lineTotal")
    public void setLineTotal (Double value) { 
        this.lineTotal = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("location")
    public LocationIdNameDto getLocation ( ) { 
        return this.location;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("location")
    public void setLocation (LocationIdNameDto value) { 
        this.location = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("openBalance")
    public Double getOpenBalance ( ) { 
        return this.openBalance;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("openBalance")
    public void setOpenBalance (Double value) { 
        this.openBalance = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("openQuantity")
    public Double getOpenQuantity ( ) { 
        return this.openQuantity;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("openQuantity")
    public void setOpenQuantity (Double value) { 
        this.openQuantity = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("orderNbr")
    public String getOrderNbr ( ) { 
        return this.orderNbr;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("orderNbr")
    public void setOrderNbr (String value) { 
        this.orderNbr = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("orderTotal")
    public Double getOrderTotal ( ) { 
        return this.orderTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("orderTotal")
    public void setOrderTotal (Double value) { 
        this.orderTotal = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("orderType")
    public OrderTypeEnum getOrderType ( ) { 
        return this.orderType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("orderType")
    public void setOrderType (OrderTypeEnum value) { 
        this.orderType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("owner")
    public UserDescriptionDto getOwner ( ) { 
        return this.owner;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("owner")
    public void setOwner (UserDescriptionDto value) { 
        this.owner = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentRefNbr")
    public String getPaymentRefNbr ( ) { 
        return this.paymentRefNbr;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentRefNbr")
    public void setPaymentRefNbr (String value) { 
        this.paymentRefNbr = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("printed")
    public Boolean getPrinted ( ) { 
        return this.printed;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("printed")
    public void setPrinted (Boolean value) { 
        this.printed = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("promisedOn")
    public Date getPromisedOn ( ) { 
        return this.promisedOn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("promisedOn")
    public void setPromisedOn (Date value) { 
        this.promisedOn = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("remitAddress")
    public PurchaseOrderAddressDto getRemitAddress ( ) { 
        return this.remitAddress;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("remitAddress")
    public void setRemitAddress (PurchaseOrderAddressDto value) { 
        this.remitAddress = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("remitContact")
    public PurchaseOrderContactDto getRemitContact ( ) { 
        return this.remitContact;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("remitContact")
    public void setRemitContact (PurchaseOrderContactDto value) { 
        this.remitContact = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("requisitionRefNbr")
    public String getRequisitionRefNbr ( ) { 
        return this.requisitionRefNbr;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("requisitionRefNbr")
    public void setRequisitionRefNbr (String value) { 
        this.requisitionRefNbr = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("salesOrderNbr")
    public String getSalesOrderNbr ( ) { 
        return this.salesOrderNbr;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("salesOrderNbr")
    public void setSalesOrderNbr (String value) { 
        this.salesOrderNbr = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("salesOrderType")
    public String getSalesOrderType ( ) { 
        return this.salesOrderType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("salesOrderType")
    public void setSalesOrderType (String value) { 
        this.salesOrderType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shippingAddress")
    public PurchaseOrderAddressDto getShippingAddress ( ) { 
        return this.shippingAddress;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shippingAddress")
    public void setShippingAddress (PurchaseOrderAddressDto value) { 
        this.shippingAddress = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shippingContact")
    public PurchaseOrderContactDto getShippingContact ( ) { 
        return this.shippingContact;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shippingContact")
    public void setShippingContact (PurchaseOrderContactDto value) { 
        this.shippingContact = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shippingDestinationType")
    public ShippingDestinationTypeEnum getShippingDestinationType ( ) { 
        return this.shippingDestinationType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shippingDestinationType")
    public void setShippingDestinationType (ShippingDestinationTypeEnum value) { 
        this.shippingDestinationType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shippingLocation")
    public LocationIdNameDto getShippingLocation ( ) { 
        return this.shippingLocation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shippingLocation")
    public void setShippingLocation (LocationIdNameDto value) { 
        this.shippingLocation = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shipTo")
    public BAccountDescriptionDto getShipTo ( ) { 
        return this.shipTo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shipTo")
    public void setShipTo (BAccountDescriptionDto value) { 
        this.shipTo = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shipVia")
    public String getShipVia ( ) { 
        return this.shipVia;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shipVia")
    public void setShipVia (String value) { 
        this.shipVia = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("status")
    public Status238Enum getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("status")
    public void setStatus (Status238Enum value) { 
        this.status = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("supplier")
    public SupplierDescriptionDto getSupplier ( ) { 
        return this.supplier;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("supplier")
    public void setSupplier (SupplierDescriptionDto value) { 
        this.supplier = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("supplierRef")
    public String getSupplierRef ( ) { 
        return this.supplierRef;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("supplierRef")
    public void setSupplierRef (String value) { 
        this.supplierRef = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("supplierVatZone")
    public VatZoneDto getSupplierVatZone ( ) { 
        return this.supplierVatZone;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("supplierVatZone")
    public void setSupplierVatZone (VatZoneDto value) { 
        this.supplierVatZone = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("taxDetails")
    public List<TaxDetailDto> getTaxDetails ( ) { 
        return this.taxDetails;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("taxDetails")
    public void setTaxDetails (List<TaxDetailDto> value) { 
        this.taxDetails = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("taxTotal")
    public Double getTaxTotal ( ) { 
        return this.taxTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("taxTotal")
    public void setTaxTotal (Double value) { 
        this.taxTotal = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("terms")
    public CreditTermsDto getTerms ( ) { 
        return this.terms;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("terms")
    public void setTerms (CreditTermsDto value) { 
        this.terms = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatExemptTotal")
    public Double getVatExemptTotal ( ) { 
        return this.vatExemptTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatExemptTotal")
    public void setVatExemptTotal (Double value) { 
        this.vatExemptTotal = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("workgroupID")
    public Integer getWorkgroupID ( ) { 
        return this.workgroupID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("workgroupID")
    public void setWorkgroupID (Integer value) { 
        this.workgroupID = value;
    }
 
}
 