/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum ReceiptActionEnum {
    REJECT, //TODO: Write general description for this element
    ACCEPTBUTWARN, //TODO: Write general description for this element
    ACCEPT; //TODO: Write general description for this element

    private static TreeMap<String, ReceiptActionEnum> valueMap = new TreeMap<String, ReceiptActionEnum>();
    private String value;

    static {
        REJECT.value = "Reject";
        ACCEPTBUTWARN.value = "AcceptButWarn";
        ACCEPT.value = "Accept";

        valueMap.put("Reject", REJECT);
        valueMap.put("AcceptButWarn", ACCEPTBUTWARN);
        valueMap.put("Accept", ACCEPT);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ReceiptActionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ReceiptActionEnum values to list of string values
     * @param toConvert The list of ReceiptActionEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<ReceiptActionEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (ReceiptActionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 