/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class SalesOrderBasicLineUpdateDtoBuilder {
    //the instance to build
    private SalesOrderBasicLineUpdateDto salesOrderBasicLineUpdateDto;

    /**
     * Default constructor to initialize the instance
     */
    public SalesOrderBasicLineUpdateDtoBuilder() {
        salesOrderBasicLineUpdateDto = new SalesOrderBasicLineUpdateDto();
    }

    public SalesOrderBasicLineUpdateDtoBuilder discountCode(DtoValueString discountCode) {
        salesOrderBasicLineUpdateDto.setDiscountCode(discountCode);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder discUnitPrice(DtoValueNullableDecimal discUnitPrice) {
        salesOrderBasicLineUpdateDto.setDiscUnitPrice(discUnitPrice);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder inventoryId(DtoValueString inventoryId) {
        salesOrderBasicLineUpdateDto.setInventoryId(inventoryId);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder lineDescription(DtoValueString lineDescription) {
        salesOrderBasicLineUpdateDto.setLineDescription(lineDescription);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder lineNbr(DtoValueNullableInt32 lineNbr) {
        salesOrderBasicLineUpdateDto.setLineNbr(lineNbr);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder manualDiscount(DtoValueNullableBoolean manualDiscount) {
        salesOrderBasicLineUpdateDto.setManualDiscount(manualDiscount);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder operation(OperationEnum operation) {
        salesOrderBasicLineUpdateDto.setOperation(operation);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder quantity(DtoValueNullableDecimal quantity) {
        salesOrderBasicLineUpdateDto.setQuantity(quantity);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder unitPrice(DtoValueNullableDecimal unitPrice) {
        salesOrderBasicLineUpdateDto.setUnitPrice(unitPrice);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder uom(DtoValueString uom) {
        salesOrderBasicLineUpdateDto.setUom(uom);
        return this;
    }

    public SalesOrderBasicLineUpdateDtoBuilder warehouse(DtoValueString warehouse) {
        salesOrderBasicLineUpdateDto.setWarehouse(warehouse);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SalesOrderBasicLineUpdateDto build() {
        return salesOrderBasicLineUpdateDto;
    }
}