/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class SalesOrderAddressUpdateDtoBuilder {
    //the instance to build
    private SalesOrderAddressUpdateDto salesOrderAddressUpdateDto;

    /**
     * Default constructor to initialize the instance
     */
    public SalesOrderAddressUpdateDtoBuilder() {
        salesOrderAddressUpdateDto = new SalesOrderAddressUpdateDto();
    }

    public SalesOrderAddressUpdateDtoBuilder addressLine1(DtoValueString addressLine1) {
        salesOrderAddressUpdateDto.setAddressLine1(addressLine1);
        return this;
    }

    public SalesOrderAddressUpdateDtoBuilder addressLine2(DtoValueString addressLine2) {
        salesOrderAddressUpdateDto.setAddressLine2(addressLine2);
        return this;
    }

    public SalesOrderAddressUpdateDtoBuilder addressLine3(DtoValueString addressLine3) {
        salesOrderAddressUpdateDto.setAddressLine3(addressLine3);
        return this;
    }

    public SalesOrderAddressUpdateDtoBuilder city(DtoValueString city) {
        salesOrderAddressUpdateDto.setCity(city);
        return this;
    }

    public SalesOrderAddressUpdateDtoBuilder countryId(DtoValueString countryId) {
        salesOrderAddressUpdateDto.setCountryId(countryId);
        return this;
    }

    public SalesOrderAddressUpdateDtoBuilder county(DtoValueString county) {
        salesOrderAddressUpdateDto.setCounty(county);
        return this;
    }

    public SalesOrderAddressUpdateDtoBuilder overrideAddress(DtoValueNullableBoolean overrideAddress) {
        salesOrderAddressUpdateDto.setOverrideAddress(overrideAddress);
        return this;
    }

    public SalesOrderAddressUpdateDtoBuilder postalCode(DtoValueString postalCode) {
        salesOrderAddressUpdateDto.setPostalCode(postalCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SalesOrderAddressUpdateDto build() {
        return salesOrderAddressUpdateDto;
    }
}