/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class SalesPersonDtoBuilder {
    //the instance to build
    private SalesPersonDto salesPersonDto;

    /**
     * Default constructor to initialize the instance
     */
    public SalesPersonDtoBuilder() {
        salesPersonDto = new SalesPersonDto();
    }

    public SalesPersonDtoBuilder description(String description) {
        salesPersonDto.setDescription(description);
        return this;
    }

    public SalesPersonDtoBuilder id(String id) {
        salesPersonDto.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SalesPersonDto build() {
        return salesPersonDto;
    }
}