/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class SalesOrderTypeDtoBuilder {
    //the instance to build
    private SalesOrderTypeDto salesOrderTypeDto;

    /**
     * Default constructor to initialize the instance
     */
    public SalesOrderTypeDtoBuilder() {
        salesOrderTypeDto = new SalesOrderTypeDto();
    }

    public SalesOrderTypeDtoBuilder active(Boolean active) {
        salesOrderTypeDto.setActive(active);
        return this;
    }

    public SalesOrderTypeDtoBuilder description(String description) {
        salesOrderTypeDto.setDescription(description);
        return this;
    }

    public SalesOrderTypeDtoBuilder orderType(String orderType) {
        salesOrderTypeDto.setOrderType(orderType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SalesOrderTypeDto build() {
        return salesOrderTypeDto;
    }
}