/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class ShipmentOrderLineDtoBuilder {
    //the instance to build
    private ShipmentOrderLineDto shipmentOrderLineDto;

    /**
     * Default constructor to initialize the instance
     */
    public ShipmentOrderLineDtoBuilder() {
        shipmentOrderLineDto = new ShipmentOrderLineDto();
    }

    public ShipmentOrderLineDtoBuilder inventoryDocType(String inventoryDocType) {
        shipmentOrderLineDto.setInventoryDocType(inventoryDocType);
        return this;
    }

    public ShipmentOrderLineDtoBuilder inventoryRefNbr(String inventoryRefNbr) {
        shipmentOrderLineDto.setInventoryRefNbr(inventoryRefNbr);
        return this;
    }

    public ShipmentOrderLineDtoBuilder invoiceNbr(String invoiceNbr) {
        shipmentOrderLineDto.setInvoiceNbr(invoiceNbr);
        return this;
    }

    public ShipmentOrderLineDtoBuilder invoiceType(String invoiceType) {
        shipmentOrderLineDto.setInvoiceType(invoiceType);
        return this;
    }

    public ShipmentOrderLineDtoBuilder orderNbr(String orderNbr) {
        shipmentOrderLineDto.setOrderNbr(orderNbr);
        return this;
    }

    public ShipmentOrderLineDtoBuilder orderType(String orderType) {
        shipmentOrderLineDto.setOrderType(orderType);
        return this;
    }

    public ShipmentOrderLineDtoBuilder shippedQty(Double shippedQty) {
        shipmentOrderLineDto.setShippedQty(shippedQty);
        return this;
    }

    public ShipmentOrderLineDtoBuilder shippedVolume(Double shippedVolume) {
        shipmentOrderLineDto.setShippedVolume(shippedVolume);
        return this;
    }

    public ShipmentOrderLineDtoBuilder shippedWeight(Double shippedWeight) {
        shipmentOrderLineDto.setShippedWeight(shippedWeight);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ShipmentOrderLineDto build() {
        return shipmentOrderLineDto;
    }
}