/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ShipmentContactDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5383669616020503222L;
    private String attention;
    private Integer contactId;
    private String email;
    private String fax;
    private String name;
    private Boolean overrideContact;
    private String phone1;
    private String phone2;
    private String web;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("attention")
    public String getAttention ( ) { 
        return this.attention;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("attention")
    public void setAttention (String value) { 
        this.attention = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("contactId")
    public Integer getContactId ( ) { 
        return this.contactId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("contactId")
    public void setContactId (Integer value) { 
        this.contactId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fax")
    public String getFax ( ) { 
        return this.fax;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fax")
    public void setFax (String value) { 
        this.fax = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("overrideContact")
    public Boolean getOverrideContact ( ) { 
        return this.overrideContact;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("overrideContact")
    public void setOverrideContact (Boolean value) { 
        this.overrideContact = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("phone1")
    public String getPhone1 ( ) { 
        return this.phone1;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("phone1")
    public void setPhone1 (String value) { 
        this.phone1 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("phone2")
    public String getPhone2 ( ) { 
        return this.phone2;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("phone2")
    public void setPhone2 (String value) { 
        this.phone2 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("web")
    public String getWeb ( ) { 
        return this.web;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("web")
    public void setWeb (String value) { 
        this.web = value;
    }
 
}
 