/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class SigmaIntrastatTransactionDescriptionDtoBuilder {
    //the instance to build
    private SigmaIntrastatTransactionDescriptionDto sigmaIntrastatTransactionDescriptionDto;

    /**
     * Default constructor to initialize the instance
     */
    public SigmaIntrastatTransactionDescriptionDtoBuilder() {
        sigmaIntrastatTransactionDescriptionDto = new SigmaIntrastatTransactionDescriptionDto();
    }

    public SigmaIntrastatTransactionDescriptionDtoBuilder description(String description) {
        sigmaIntrastatTransactionDescriptionDto.setDescription(description);
        return this;
    }

    public SigmaIntrastatTransactionDescriptionDtoBuilder id(Integer id) {
        sigmaIntrastatTransactionDescriptionDto.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SigmaIntrastatTransactionDescriptionDto build() {
        return sigmaIntrastatTransactionDescriptionDto;
    }
}