/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum Status144Enum {
    ACTIVE, //TODO: Write general description for this element
    NOSALES, //TODO: Write general description for this element
    NOPURCHASES, //TODO: Write general description for this element
    NOREQUEST, //TODO: Write general description for this element
    INACTIVE, //TODO: Write general description for this element
    MARKEDFORDELETION; //TODO: Write general description for this element

    private static TreeMap<String, Status144Enum> valueMap = new TreeMap<String, Status144Enum>();
    private String value;

    static {
        ACTIVE.value = "Active";
        NOSALES.value = "NoSales";
        NOPURCHASES.value = "NoPurchases";
        NOREQUEST.value = "NoRequest";
        INACTIVE.value = "Inactive";
        MARKEDFORDELETION.value = "MarkedForDeletion";

        valueMap.put("Active", ACTIVE);
        valueMap.put("NoSales", NOSALES);
        valueMap.put("NoPurchases", NOPURCHASES);
        valueMap.put("NoRequest", NOREQUEST);
        valueMap.put("Inactive", INACTIVE);
        valueMap.put("MarkedForDeletion", MARKEDFORDELETION);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static Status144Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Status144Enum values to list of string values
     * @param toConvert The list of Status144Enum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<Status144Enum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (Status144Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 