/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class StocktakeUpdateDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4833276474672945930L;
    private List<StocktakeLineUpdateDto> lines;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lines")
    public List<StocktakeLineUpdateDto> getLines ( ) { 
        return this.lines;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lines")
    public void setLines (List<StocktakeLineUpdateDto> value) { 
        this.lines = value;
    }
 
}
 