/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class StocktakeUpdateDtoBuilder {
    //the instance to build
    private StocktakeUpdateDto stocktakeUpdateDto;

    /**
     * Default constructor to initialize the instance
     */
    public StocktakeUpdateDtoBuilder() {
        stocktakeUpdateDto = new StocktakeUpdateDto();
    }

    public StocktakeUpdateDtoBuilder lines(List<StocktakeLineUpdateDto> lines) {
        stocktakeUpdateDto.setLines(lines);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StocktakeUpdateDto build() {
        return stocktakeUpdateDto;
    }
}