/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class StocktakeDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4741566024431662566L;
    private String description;
    private Date freezeDate;
    private Date lastModifiedDateTime;
    private List<StocktakeLineDto> lines;
    private Integer numberOfLines;
    private Double physicalQty;
    private String referenceNbr;
    private SummaryStatusEnum summaryStatus;
    private Double varianceCost;
    private Double varianceQty;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("freezeDate")
    public Date getFreezeDate ( ) { 
        return this.freezeDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("freezeDate")
    public void setFreezeDate (Date value) { 
        this.freezeDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lastModifiedDateTime")
    public Date getLastModifiedDateTime ( ) { 
        return this.lastModifiedDateTime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lastModifiedDateTime")
    public void setLastModifiedDateTime (Date value) { 
        this.lastModifiedDateTime = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lines")
    public List<StocktakeLineDto> getLines ( ) { 
        return this.lines;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lines")
    public void setLines (List<StocktakeLineDto> value) { 
        this.lines = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("numberOfLines")
    public Integer getNumberOfLines ( ) { 
        return this.numberOfLines;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("numberOfLines")
    public void setNumberOfLines (Integer value) { 
        this.numberOfLines = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("physicalQty")
    public Double getPhysicalQty ( ) { 
        return this.physicalQty;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("physicalQty")
    public void setPhysicalQty (Double value) { 
        this.physicalQty = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("referenceNbr")
    public String getReferenceNbr ( ) { 
        return this.referenceNbr;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("referenceNbr")
    public void setReferenceNbr (String value) { 
        this.referenceNbr = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("summaryStatus")
    public SummaryStatusEnum getSummaryStatus ( ) { 
        return this.summaryStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("summaryStatus")
    public void setSummaryStatus (SummaryStatusEnum value) { 
        this.summaryStatus = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("varianceCost")
    public Double getVarianceCost ( ) { 
        return this.varianceCost;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("varianceCost")
    public void setVarianceCost (Double value) { 
        this.varianceCost = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("varianceQty")
    public Double getVarianceQty ( ) { 
        return this.varianceQty;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("varianceQty")
    public void setVarianceQty (Double value) { 
        this.varianceQty = value;
    }
 
}
 