/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class SupplierInvoiceLineDtoBuilder {
    //the instance to build
    private SupplierInvoiceLineDto supplierInvoiceLineDto;

    /**
     * Default constructor to initialize the instance
     */
    public SupplierInvoiceLineDtoBuilder() {
        supplierInvoiceLineDto = new SupplierInvoiceLineDto();
    }

    public SupplierInvoiceLineDtoBuilder account(AccountNumberDto account) {
        supplierInvoiceLineDto.setAccount(account);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder branchNumber(String branchNumber) {
        supplierInvoiceLineDto.setBranchNumber(branchNumber);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder cost(Double cost) {
        supplierInvoiceLineDto.setCost(cost);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder costInCurrency(Double costInCurrency) {
        supplierInvoiceLineDto.setCostInCurrency(costInCurrency);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder deferralCode(String deferralCode) {
        supplierInvoiceLineDto.setDeferralCode(deferralCode);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder deferralSchedule(Integer deferralSchedule) {
        supplierInvoiceLineDto.setDeferralSchedule(deferralSchedule);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder inventoryNumber(String inventoryNumber) {
        supplierInvoiceLineDto.setInventoryNumber(inventoryNumber);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder lineNumber(Integer lineNumber) {
        supplierInvoiceLineDto.setLineNumber(lineNumber);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder note(String note) {
        supplierInvoiceLineDto.setNote(note);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder poLineNr(Integer poLineNr) {
        supplierInvoiceLineDto.setPoLineNr(poLineNr);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder poNumber(String poNumber) {
        supplierInvoiceLineDto.setPoNumber(poNumber);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder poReceiptLineNbr(Integer poReceiptLineNbr) {
        supplierInvoiceLineDto.setPoReceiptLineNbr(poReceiptLineNbr);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder poReceiptNbr(String poReceiptNbr) {
        supplierInvoiceLineDto.setPoReceiptNbr(poReceiptNbr);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder quantity(Double quantity) {
        supplierInvoiceLineDto.setQuantity(quantity);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder subaccount(SubAccountDto subaccount) {
        supplierInvoiceLineDto.setSubaccount(subaccount);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder transactionDescription(String transactionDescription) {
        supplierInvoiceLineDto.setTransactionDescription(transactionDescription);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder unitCost(Double unitCost) {
        supplierInvoiceLineDto.setUnitCost(unitCost);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder unitCostInCurrency(Double unitCostInCurrency) {
        supplierInvoiceLineDto.setUnitCostInCurrency(unitCostInCurrency);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder uom(String uom) {
        supplierInvoiceLineDto.setUom(uom);
        return this;
    }

    public SupplierInvoiceLineDtoBuilder vatCode(VatCodeDto vatCode) {
        supplierInvoiceLineDto.setVatCode(vatCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SupplierInvoiceLineDto build() {
        return supplierInvoiceLineDto;
    }
}