/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class SupplierPOBalanceDtoBuilder {
    //the instance to build
    private SupplierPOBalanceDto supplierPOBalanceDto;

    /**
     * Default constructor to initialize the instance
     */
    public SupplierPOBalanceDtoBuilder() {
        supplierPOBalanceDto = new SupplierPOBalanceDto();
    }

    public SupplierPOBalanceDtoBuilder lastModifiedDateTime(Date lastModifiedDateTime) {
        supplierPOBalanceDto.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public SupplierPOBalanceDtoBuilder supplier(SupplierDescriptionDto supplier) {
        supplierPOBalanceDto.setSupplier(supplier);
        return this;
    }

    public SupplierPOBalanceDtoBuilder totalClosedPOLineTotal(Double totalClosedPOLineTotal) {
        supplierPOBalanceDto.setTotalClosedPOLineTotal(totalClosedPOLineTotal);
        return this;
    }

    public SupplierPOBalanceDtoBuilder totalClosedPOOrderTotal(Double totalClosedPOOrderTotal) {
        supplierPOBalanceDto.setTotalClosedPOOrderTotal(totalClosedPOOrderTotal);
        return this;
    }

    public SupplierPOBalanceDtoBuilder totalOpenPOLineTotal(Double totalOpenPOLineTotal) {
        supplierPOBalanceDto.setTotalOpenPOLineTotal(totalOpenPOLineTotal);
        return this;
    }

    public SupplierPOBalanceDtoBuilder totalOpenPOOrderTotal(Double totalOpenPOOrderTotal) {
        supplierPOBalanceDto.setTotalOpenPOOrderTotal(totalOpenPOOrderTotal);
        return this;
    }

    public SupplierPOBalanceDtoBuilder totalPOOnHoldLineTotal(Double totalPOOnHoldLineTotal) {
        supplierPOBalanceDto.setTotalPOOnHoldLineTotal(totalPOOnHoldLineTotal);
        return this;
    }

    public SupplierPOBalanceDtoBuilder totalPOOnHoldOrderTotal(Double totalPOOnHoldOrderTotal) {
        supplierPOBalanceDto.setTotalPOOnHoldOrderTotal(totalPOOnHoldOrderTotal);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SupplierPOBalanceDto build() {
        return supplierPOBalanceDto;
    }
}