/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SupplierPaymentMethodDetailUpdateDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4727045830329950056L;
    private String paymentMethodDetailDescription;
    private DtoValueString paymentMethodDetailValue;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentMethodDetailDescription")
    public String getPaymentMethodDetailDescription ( ) { 
        return this.paymentMethodDetailDescription;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentMethodDetailDescription")
    public void setPaymentMethodDetailDescription (String value) { 
        this.paymentMethodDetailDescription = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentMethodDetailValue")
    public DtoValueString getPaymentMethodDetailValue ( ) { 
        return this.paymentMethodDetailValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentMethodDetailValue")
    public void setPaymentMethodDetailValue (DtoValueString value) { 
        this.paymentMethodDetailValue = value;
    }
 
}
 