/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class SupplierDtoBuilder {
    //the instance to build
    private SupplierDto supplierDto;

    /**
     * Default constructor to initialize the instance
     */
    public SupplierDtoBuilder() {
        supplierDto = new SupplierDto();
    }

    public SupplierDtoBuilder accountReference(String accountReference) {
        supplierDto.setAccountReference(accountReference);
        return this;
    }

    public SupplierDtoBuilder accountUsedForPayment(AccountUsedForPaymentEnum accountUsedForPayment) {
        supplierDto.setAccountUsedForPayment(accountUsedForPayment);
        return this;
    }

    public SupplierDtoBuilder cashAccount(String cashAccount) {
        supplierDto.setCashAccount(cashAccount);
        return this;
    }

    public SupplierDtoBuilder chargeBearer(ChargeBearerEnum chargeBearer) {
        supplierDto.setChargeBearer(chargeBearer);
        return this;
    }

    public SupplierDtoBuilder corporateId(String corporateId) {
        supplierDto.setCorporateId(corporateId);
        return this;
    }

    public SupplierDtoBuilder creditTerms(CreditTermsDto creditTerms) {
        supplierDto.setCreditTerms(creditTerms);
        return this;
    }

    public SupplierDtoBuilder currencyId(String currencyId) {
        supplierDto.setCurrencyId(currencyId);
        return this;
    }

    public SupplierDtoBuilder documentLanguage(String documentLanguage) {
        supplierDto.setDocumentLanguage(documentLanguage);
        return this;
    }

    public SupplierDtoBuilder internalId(Integer internalId) {
        supplierDto.setInternalId(internalId);
        return this;
    }

    public SupplierDtoBuilder lastModifiedDateTime(Date lastModifiedDateTime) {
        supplierDto.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public SupplierDtoBuilder location(LocationDto location) {
        supplierDto.setLocation(location);
        return this;
    }

    public SupplierDtoBuilder mainAddress(AddressDto mainAddress) {
        supplierDto.setMainAddress(mainAddress);
        return this;
    }

    public SupplierDtoBuilder mainContact(ContactInfoDto mainContact) {
        supplierDto.setMainContact(mainContact);
        return this;
    }

    public SupplierDtoBuilder name(String name) {
        supplierDto.setName(name);
        return this;
    }

    public SupplierDtoBuilder number(String number) {
        supplierDto.setNumber(number);
        return this;
    }

    public SupplierDtoBuilder parentRecord(ParentRecordDto parentRecord) {
        supplierDto.setParentRecord(parentRecord);
        return this;
    }

    public SupplierDtoBuilder paymentBy(PaymentByEnum paymentBy) {
        supplierDto.setPaymentBy(paymentBy);
        return this;
    }

    public SupplierDtoBuilder paymentLeadTime(Integer paymentLeadTime) {
        supplierDto.setPaymentLeadTime(paymentLeadTime);
        return this;
    }

    public SupplierDtoBuilder paymentMethod(PaymentMethodIdDescriptionDto paymentMethod) {
        supplierDto.setPaymentMethod(paymentMethod);
        return this;
    }

    public SupplierDtoBuilder paymentRefDisplayMask(String paymentRefDisplayMask) {
        supplierDto.setPaymentRefDisplayMask(paymentRefDisplayMask);
        return this;
    }

    public SupplierDtoBuilder paySeparately(Boolean paySeparately) {
        supplierDto.setPaySeparately(paySeparately);
        return this;
    }

    public SupplierDtoBuilder remitAddress(AddressDto remitAddress) {
        supplierDto.setRemitAddress(remitAddress);
        return this;
    }

    public SupplierDtoBuilder remitContact(ContactInfoDto remitContact) {
        supplierDto.setRemitContact(remitContact);
        return this;
    }

    public SupplierDtoBuilder status(Status130Enum status) {
        supplierDto.setStatus(status);
        return this;
    }

    public SupplierDtoBuilder supplierAddress(AddressDto supplierAddress) {
        supplierDto.setSupplierAddress(supplierAddress);
        return this;
    }

    public SupplierDtoBuilder supplierClass(ClassDescriptionDto supplierClass) {
        supplierDto.setSupplierClass(supplierClass);
        return this;
    }

    public SupplierDtoBuilder supplierContact(ContactInfoDto supplierContact) {
        supplierDto.setSupplierContact(supplierContact);
        return this;
    }

    public SupplierDtoBuilder vatRegistrationId(String vatRegistrationId) {
        supplierDto.setVatRegistrationId(vatRegistrationId);
        return this;
    }

    public SupplierDtoBuilder vatZone(VatZoneDto vatZone) {
        supplierDto.setVatZone(vatZone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SupplierDto build() {
        return supplierDto;
    }
}