/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SupplierInvoiceUpdateDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5237384166385196484L;
    private DtoValueDateTime cashDiscountDate;
    private DtoValueString creditTermsId;
    private DtoValueString currencyId;
    private DtoValueDateTime date;
    private DtoValueString description;
    private DtoValueDateTime dueDate;
    private DtoValueDecimal exchangeRate;
    private DtoValueString financialPeriod;
    private DtoValueBoolean hold;
    private List<SupplierInvoiceLineUpdateDto> invoiceLines;
    private DtoValueString locationId;
    private DtoValueString note;
    private DtoValueString paymentRefNo;
    private DtoValueString postPeriod;
    private DtoValueString referenceNumber;
    private DtoValueString supplierNumber;
    private DtoValueString supplierReference;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cashDiscountDate")
    public DtoValueDateTime getCashDiscountDate ( ) { 
        return this.cashDiscountDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cashDiscountDate")
    public void setCashDiscountDate (DtoValueDateTime value) { 
        this.cashDiscountDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("creditTermsId")
    public DtoValueString getCreditTermsId ( ) { 
        return this.creditTermsId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("creditTermsId")
    public void setCreditTermsId (DtoValueString value) { 
        this.creditTermsId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("currencyId")
    public DtoValueString getCurrencyId ( ) { 
        return this.currencyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("currencyId")
    public void setCurrencyId (DtoValueString value) { 
        this.currencyId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date")
    public DtoValueDateTime getDate ( ) { 
        return this.date;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date")
    public void setDate (DtoValueDateTime value) { 
        this.date = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public DtoValueString getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (DtoValueString value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("dueDate")
    public DtoValueDateTime getDueDate ( ) { 
        return this.dueDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("dueDate")
    public void setDueDate (DtoValueDateTime value) { 
        this.dueDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exchangeRate")
    public DtoValueDecimal getExchangeRate ( ) { 
        return this.exchangeRate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exchangeRate")
    public void setExchangeRate (DtoValueDecimal value) { 
        this.exchangeRate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("financialPeriod")
    public DtoValueString getFinancialPeriod ( ) { 
        return this.financialPeriod;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("financialPeriod")
    public void setFinancialPeriod (DtoValueString value) { 
        this.financialPeriod = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hold")
    public DtoValueBoolean getHold ( ) { 
        return this.hold;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hold")
    public void setHold (DtoValueBoolean value) { 
        this.hold = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("invoiceLines")
    public List<SupplierInvoiceLineUpdateDto> getInvoiceLines ( ) { 
        return this.invoiceLines;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("invoiceLines")
    public void setInvoiceLines (List<SupplierInvoiceLineUpdateDto> value) { 
        this.invoiceLines = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("locationId")
    public DtoValueString getLocationId ( ) { 
        return this.locationId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("locationId")
    public void setLocationId (DtoValueString value) { 
        this.locationId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("note")
    public DtoValueString getNote ( ) { 
        return this.note;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("note")
    public void setNote (DtoValueString value) { 
        this.note = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentRefNo")
    public DtoValueString getPaymentRefNo ( ) { 
        return this.paymentRefNo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentRefNo")
    public void setPaymentRefNo (DtoValueString value) { 
        this.paymentRefNo = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("postPeriod")
    public DtoValueString getPostPeriod ( ) { 
        return this.postPeriod;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("postPeriod")
    public void setPostPeriod (DtoValueString value) { 
        this.postPeriod = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("referenceNumber")
    public DtoValueString getReferenceNumber ( ) { 
        return this.referenceNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("referenceNumber")
    public void setReferenceNumber (DtoValueString value) { 
        this.referenceNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("supplierNumber")
    public DtoValueString getSupplierNumber ( ) { 
        return this.supplierNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("supplierNumber")
    public void setSupplierNumber (DtoValueString value) { 
        this.supplierNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("supplierReference")
    public DtoValueString getSupplierReference ( ) { 
        return this.supplierReference;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("supplierReference")
    public void setSupplierReference (DtoValueString value) { 
        this.supplierReference = value;
    }
 
}
 