/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class SupplierBalanceDtoBuilder {
    //the instance to build
    private SupplierBalanceDto supplierBalanceDto;

    /**
     * Default constructor to initialize the instance
     */
    public SupplierBalanceDtoBuilder() {
        supplierBalanceDto = new SupplierBalanceDto();
    }

    public SupplierBalanceDtoBuilder balance(Double balance) {
        supplierBalanceDto.setBalance(balance);
        return this;
    }

    public SupplierBalanceDtoBuilder lastModifiedDateTime(Date lastModifiedDateTime) {
        supplierBalanceDto.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public SupplierBalanceDtoBuilder supplier(SupplierDescriptionDto supplier) {
        supplierBalanceDto.setSupplier(supplier);
        return this;
    }

    public SupplierBalanceDtoBuilder totalPurchaseInvoicePeriod(WithoutWithVatDto totalPurchaseInvoicePeriod) {
        supplierBalanceDto.setTotalPurchaseInvoicePeriod(totalPurchaseInvoicePeriod);
        return this;
    }

    public SupplierBalanceDtoBuilder totalPurchaseInvoiceYear(WithoutWithVatDto totalPurchaseInvoiceYear) {
        supplierBalanceDto.setTotalPurchaseInvoiceYear(totalPurchaseInvoiceYear);
        return this;
    }

    public SupplierBalanceDtoBuilder totalSentForApproval(WithoutWithVatDto totalSentForApproval) {
        supplierBalanceDto.setTotalSentForApproval(totalSentForApproval);
        return this;
    }

    public SupplierBalanceDtoBuilder unreleasedPurchasesNotInApproval(WithoutWithVatDto unreleasedPurchasesNotInApproval) {
        supplierBalanceDto.setUnreleasedPurchasesNotInApproval(unreleasedPurchasesNotInApproval);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SupplierBalanceDto build() {
        return supplierBalanceDto;
    }
}