/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SupplierInvoiceDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5321113029414746873L;
    private ApprovalStatusEnum approvalStatus;
    private Double balance;
    private Double balanceInCurrency;
    private Double cashDiscount;
    private Date cashDiscountDate;
    private Double cashDiscountInCurrency;
    private Date createdDateTime;
    private CreditTermsDto creditTerms;
    private String currencyId;
    private Date date;
    private String description;
    private Double detailTotal;
    private Double detailTotalInCurrency;
    private DocumentType345Enum documentType;
    private Date dueDate;
    private String financialPeriod;
    private Boolean hold;
    private List<SupplierInvoiceLineDto> invoiceLines;
    private Date lastModifiedDateTime;
    private LocationDto location;
    private String note;
    private PaymentMethodIdDescriptionDto paymentMethod;
    private String paymentRefNo;
    private String postPeriod;
    private String referenceNumber;
    private Status347Enum status;
    private SupplierNumberDto supplier;
    private String supplierReference;
    private Double vatExemptTotal;
    private Double vatExemptTotalInCurrency;
    private Double vatTaxableTotal;
    private Double vatTaxableTotalInCurrency;
    private Double vatTotal;
    private Double vatTotalInCurrency;
    private Double withholdingTax;
    private Double withholdingTaxInCurrency;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("approvalStatus")
    public ApprovalStatusEnum getApprovalStatus ( ) { 
        return this.approvalStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("approvalStatus")
    public void setApprovalStatus (ApprovalStatusEnum value) { 
        this.approvalStatus = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("balance")
    public Double getBalance ( ) { 
        return this.balance;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("balance")
    public void setBalance (Double value) { 
        this.balance = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("balanceInCurrency")
    public Double getBalanceInCurrency ( ) { 
        return this.balanceInCurrency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("balanceInCurrency")
    public void setBalanceInCurrency (Double value) { 
        this.balanceInCurrency = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cashDiscount")
    public Double getCashDiscount ( ) { 
        return this.cashDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cashDiscount")
    public void setCashDiscount (Double value) { 
        this.cashDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cashDiscountDate")
    public Date getCashDiscountDate ( ) { 
        return this.cashDiscountDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cashDiscountDate")
    public void setCashDiscountDate (Date value) { 
        this.cashDiscountDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cashDiscountInCurrency")
    public Double getCashDiscountInCurrency ( ) { 
        return this.cashDiscountInCurrency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cashDiscountInCurrency")
    public void setCashDiscountInCurrency (Double value) { 
        this.cashDiscountInCurrency = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createdDateTime")
    public Date getCreatedDateTime ( ) { 
        return this.createdDateTime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createdDateTime")
    public void setCreatedDateTime (Date value) { 
        this.createdDateTime = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("creditTerms")
    public CreditTermsDto getCreditTerms ( ) { 
        return this.creditTerms;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("creditTerms")
    public void setCreditTerms (CreditTermsDto value) { 
        this.creditTerms = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("currencyId")
    public String getCurrencyId ( ) { 
        return this.currencyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("currencyId")
    public void setCurrencyId (String value) { 
        this.currencyId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date")
    public Date getDate ( ) { 
        return this.date;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date")
    public void setDate (Date value) { 
        this.date = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("detailTotal")
    public Double getDetailTotal ( ) { 
        return this.detailTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("detailTotal")
    public void setDetailTotal (Double value) { 
        this.detailTotal = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("detailTotalInCurrency")
    public Double getDetailTotalInCurrency ( ) { 
        return this.detailTotalInCurrency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("detailTotalInCurrency")
    public void setDetailTotalInCurrency (Double value) { 
        this.detailTotalInCurrency = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("documentType")
    public DocumentType345Enum getDocumentType ( ) { 
        return this.documentType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("documentType")
    public void setDocumentType (DocumentType345Enum value) { 
        this.documentType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("dueDate")
    public Date getDueDate ( ) { 
        return this.dueDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("dueDate")
    public void setDueDate (Date value) { 
        this.dueDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("financialPeriod")
    public String getFinancialPeriod ( ) { 
        return this.financialPeriod;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("financialPeriod")
    public void setFinancialPeriod (String value) { 
        this.financialPeriod = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hold")
    public Boolean getHold ( ) { 
        return this.hold;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hold")
    public void setHold (Boolean value) { 
        this.hold = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("invoiceLines")
    public List<SupplierInvoiceLineDto> getInvoiceLines ( ) { 
        return this.invoiceLines;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("invoiceLines")
    public void setInvoiceLines (List<SupplierInvoiceLineDto> value) { 
        this.invoiceLines = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lastModifiedDateTime")
    public Date getLastModifiedDateTime ( ) { 
        return this.lastModifiedDateTime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lastModifiedDateTime")
    public void setLastModifiedDateTime (Date value) { 
        this.lastModifiedDateTime = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("location")
    public LocationDto getLocation ( ) { 
        return this.location;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("location")
    public void setLocation (LocationDto value) { 
        this.location = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("note")
    public String getNote ( ) { 
        return this.note;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("note")
    public void setNote (String value) { 
        this.note = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentMethod")
    public PaymentMethodIdDescriptionDto getPaymentMethod ( ) { 
        return this.paymentMethod;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentMethod")
    public void setPaymentMethod (PaymentMethodIdDescriptionDto value) { 
        this.paymentMethod = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentRefNo")
    public String getPaymentRefNo ( ) { 
        return this.paymentRefNo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentRefNo")
    public void setPaymentRefNo (String value) { 
        this.paymentRefNo = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("postPeriod")
    public String getPostPeriod ( ) { 
        return this.postPeriod;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("postPeriod")
    public void setPostPeriod (String value) { 
        this.postPeriod = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("referenceNumber")
    public String getReferenceNumber ( ) { 
        return this.referenceNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("referenceNumber")
    public void setReferenceNumber (String value) { 
        this.referenceNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("status")
    public Status347Enum getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("status")
    public void setStatus (Status347Enum value) { 
        this.status = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("supplier")
    public SupplierNumberDto getSupplier ( ) { 
        return this.supplier;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("supplier")
    public void setSupplier (SupplierNumberDto value) { 
        this.supplier = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("supplierReference")
    public String getSupplierReference ( ) { 
        return this.supplierReference;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("supplierReference")
    public void setSupplierReference (String value) { 
        this.supplierReference = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatExemptTotal")
    public Double getVatExemptTotal ( ) { 
        return this.vatExemptTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatExemptTotal")
    public void setVatExemptTotal (Double value) { 
        this.vatExemptTotal = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatExemptTotalInCurrency")
    public Double getVatExemptTotalInCurrency ( ) { 
        return this.vatExemptTotalInCurrency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatExemptTotalInCurrency")
    public void setVatExemptTotalInCurrency (Double value) { 
        this.vatExemptTotalInCurrency = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatTaxableTotal")
    public Double getVatTaxableTotal ( ) { 
        return this.vatTaxableTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatTaxableTotal")
    public void setVatTaxableTotal (Double value) { 
        this.vatTaxableTotal = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatTaxableTotalInCurrency")
    public Double getVatTaxableTotalInCurrency ( ) { 
        return this.vatTaxableTotalInCurrency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatTaxableTotalInCurrency")
    public void setVatTaxableTotalInCurrency (Double value) { 
        this.vatTaxableTotalInCurrency = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatTotal")
    public Double getVatTotal ( ) { 
        return this.vatTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatTotal")
    public void setVatTotal (Double value) { 
        this.vatTotal = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatTotalInCurrency")
    public Double getVatTotalInCurrency ( ) { 
        return this.vatTotalInCurrency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatTotalInCurrency")
    public void setVatTotalInCurrency (Double value) { 
        this.vatTotalInCurrency = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("withholdingTax")
    public Double getWithholdingTax ( ) { 
        return this.withholdingTax;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("withholdingTax")
    public void setWithholdingTax (Double value) { 
        this.withholdingTax = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("withholdingTaxInCurrency")
    public Double getWithholdingTaxInCurrency ( ) { 
        return this.withholdingTaxInCurrency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("withholdingTaxInCurrency")
    public void setWithholdingTaxInCurrency (Double value) { 
        this.withholdingTaxInCurrency = value;
    }
 
}
 