/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaxDetailDto 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4657444093012533350L;
    private Integer recordId;
    private Double taxableAmount;
    private Double vatAmount;
    private TaxNumberDescriptionDto vatId;
    private Double vatRate;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("recordId")
    public Integer getRecordId ( ) { 
        return this.recordId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("recordId")
    public void setRecordId (Integer value) { 
        this.recordId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("taxableAmount")
    public Double getTaxableAmount ( ) { 
        return this.taxableAmount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("taxableAmount")
    public void setTaxableAmount (Double value) { 
        this.taxableAmount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatAmount")
    public Double getVatAmount ( ) { 
        return this.vatAmount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatAmount")
    public void setVatAmount (Double value) { 
        this.vatAmount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatId")
    public TaxNumberDescriptionDto getVatId ( ) { 
        return this.vatId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatId")
    public void setVatId (TaxNumberDescriptionDto value) { 
        this.vatId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("vatRate")
    public Double getVatRate ( ) { 
        return this.vatRate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("vatRate")
    public void setVatRate (Double value) { 
        this.vatRate = value;
    }
 
}
 