/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum TransferOrderTypeEnum {
    CREDITNOTE, //TODO: Write general description for this element
    DEBITNOTE, //TODO: Write general description for this element
    INVOICE, //TODO: Write general description for this element
    QUOTEORDER, //TODO: Write general description for this element
    RMAORDER, //TODO: Write general description for this element
    SALESORDER, //TODO: Write general description for this element
    STANDARDORDER, //TODO: Write general description for this element
    TRANSFERORDER; //TODO: Write general description for this element

    private static TreeMap<String, TransferOrderTypeEnum> valueMap = new TreeMap<String, TransferOrderTypeEnum>();
    private String value;

    static {
        CREDITNOTE.value = "CreditNote";
        DEBITNOTE.value = "DebitNote";
        INVOICE.value = "Invoice";
        QUOTEORDER.value = "QuoteOrder";
        RMAORDER.value = "RMAOrder";
        SALESORDER.value = "SalesOrder";
        STANDARDORDER.value = "StandardOrder";
        TRANSFERORDER.value = "TransferOrder";

        valueMap.put("CreditNote", CREDITNOTE);
        valueMap.put("DebitNote", DEBITNOTE);
        valueMap.put("Invoice", INVOICE);
        valueMap.put("QuoteOrder", QUOTEORDER);
        valueMap.put("RMAOrder", RMAORDER);
        valueMap.put("SalesOrder", SALESORDER);
        valueMap.put("StandardOrder", STANDARDORDER);
        valueMap.put("TransferOrder", TRANSFERORDER);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static TransferOrderTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TransferOrderTypeEnum values to list of string values
     * @param toConvert The list of TransferOrderTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<TransferOrderTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (TransferOrderTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 