/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum Type236Enum {
    DOCUMENT, //TODO: Write general description for this element
    FLAT, //TODO: Write general description for this element
    GROUP, //TODO: Write general description for this element
    LINE; //TODO: Write general description for this element

    private static TreeMap<String, Type236Enum> valueMap = new TreeMap<String, Type236Enum>();
    private String value;

    static {
        DOCUMENT.value = "Document";
        FLAT.value = "Flat";
        GROUP.value = "Group";
        LINE.value = "Line";

        valueMap.put("Document", DOCUMENT);
        valueMap.put("Flat", FLAT);
        valueMap.put("Group", GROUP);
        valueMap.put("Line", LINE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static Type236Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Type236Enum values to list of string values
     * @param toConvert The list of Type236Enum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<Type236Enum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (Type236Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 