/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum Value333Enum {
    ACTIVE, //TODO: Write general description for this element
    HOLDPAYMENTS, //TODO: Write general description for this element
    INACTIVE, //TODO: Write general description for this element
    ONETIME, //TODO: Write general description for this element
    ONHOLD; //TODO: Write general description for this element

    private static TreeMap<String, Value333Enum> valueMap = new TreeMap<String, Value333Enum>();
    private String value;

    static {
        ACTIVE.value = "Active";
        HOLDPAYMENTS.value = "HoldPayments";
        INACTIVE.value = "Inactive";
        ONETIME.value = "OneTime";
        ONHOLD.value = "OnHold";

        valueMap.put("Active", ACTIVE);
        valueMap.put("HoldPayments", HOLDPAYMENTS);
        valueMap.put("Inactive", INACTIVE);
        valueMap.put("OneTime", ONETIME);
        valueMap.put("OnHold", ONHOLD);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static Value333Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Value333Enum values to list of string values
     * @param toConvert The list of Value333Enum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<Value333Enum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (Value333Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 