/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum Value177Enum {
    CREDITNOTE, //TODO: Write general description for this element
    DEBITNOTE, //TODO: Write general description for this element
    INVOICE, //TODO: Write general description for this element
    ISSUE, //TODO: Write general description for this element
    RETURN; //TODO: Write general description for this element

    private static TreeMap<String, Value177Enum> valueMap = new TreeMap<String, Value177Enum>();
    private String value;

    static {
        CREDITNOTE.value = "CreditNote";
        DEBITNOTE.value = "DebitNote";
        INVOICE.value = "Invoice";
        ISSUE.value = "Issue";
        RETURN.value = "Return";

        valueMap.put("CreditNote", CREDITNOTE);
        valueMap.put("DebitNote", DEBITNOTE);
        valueMap.put("Invoice", INVOICE);
        valueMap.put("Issue", ISSUE);
        valueMap.put("Return", RETURN);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static Value177Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Value177Enum values to list of string values
     * @param toConvert The list of Value177Enum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<Value177Enum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (Value177Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 