/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum Value283Enum {
    DROPSHIPTOORDER, //TODO: Write general description for this element
    MANUFACTURED, //TODO: Write general description for this element
    NONE, //TODO: Write general description for this element
    PURCHASED, //TODO: Write general description for this element
    PURCHASETOORDER, //TODO: Write general description for this element
    TRANSFER; //TODO: Write general description for this element

    private static TreeMap<String, Value283Enum> valueMap = new TreeMap<String, Value283Enum>();
    private String value;

    static {
        DROPSHIPTOORDER.value = "DropShipToOrder";
        MANUFACTURED.value = "Manufactured";
        NONE.value = "None";
        PURCHASED.value = "Purchased";
        PURCHASETOORDER.value = "PurchaseToOrder";
        TRANSFER.value = "Transfer";

        valueMap.put("DropShipToOrder", DROPSHIPTOORDER);
        valueMap.put("Manufactured", MANUFACTURED);
        valueMap.put("None", NONE);
        valueMap.put("Purchased", PURCHASED);
        valueMap.put("PurchaseToOrder", PURCHASETOORDER);
        valueMap.put("Transfer", TRANSFER);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static Value283Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Value283Enum values to list of string values
     * @param toConvert The list of Value283Enum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<Value283Enum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (Value283Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 