/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class VatCategoryLineDtoBuilder {
    //the instance to build
    private VatCategoryLineDto vatCategoryLineDto;

    /**
     * Default constructor to initialize the instance
     */
    public VatCategoryLineDtoBuilder() {
        vatCategoryLineDto = new VatCategoryLineDto();
    }

    public VatCategoryLineDtoBuilder calculateOn(CalculateOnEnum calculateOn) {
        vatCategoryLineDto.setCalculateOn(calculateOn);
        return this;
    }

    public VatCategoryLineDtoBuilder cashDiscount(CashDiscountEnum cashDiscount) {
        vatCategoryLineDto.setCashDiscount(cashDiscount);
        return this;
    }

    public VatCategoryLineDtoBuilder description(String description) {
        vatCategoryLineDto.setDescription(description);
        return this;
    }

    public VatCategoryLineDtoBuilder type(Type358Enum type) {
        vatCategoryLineDto.setType(type);
        return this;
    }

    public VatCategoryLineDtoBuilder vatId(String vatId) {
        vatCategoryLineDto.setVatId(vatId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public VatCategoryLineDto build() {
        return vatCategoryLineDto;
    }
}