/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class VatCategoryDtoBuilder {
    //the instance to build
    private VatCategoryDto vatCategoryDto;

    /**
     * Default constructor to initialize the instance
     */
    public VatCategoryDtoBuilder() {
        vatCategoryDto = new VatCategoryDto();
    }

    public VatCategoryDtoBuilder active(Boolean active) {
        vatCategoryDto.setActive(active);
        return this;
    }

    public VatCategoryDtoBuilder description(String description) {
        vatCategoryDto.setDescription(description);
        return this;
    }

    public VatCategoryDtoBuilder excludeListedTaxes(Boolean excludeListedTaxes) {
        vatCategoryDto.setExcludeListedTaxes(excludeListedTaxes);
        return this;
    }

    public VatCategoryDtoBuilder lastModifiedDateTime(Date lastModifiedDateTime) {
        vatCategoryDto.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public VatCategoryDtoBuilder vatCategoryId(String vatCategoryId) {
        vatCategoryDto.setVatCategoryId(vatCategoryId);
        return this;
    }

    public VatCategoryDtoBuilder vatCategoryLines(List<VatCategoryLineDto> vatCategoryLines) {
        vatCategoryDto.setVatCategoryLines(vatCategoryLines);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public VatCategoryDto build() {
        return vatCategoryDto;
    }
}