/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class VatCodeDtoBuilder {
    //the instance to build
    private VatCodeDto vatCodeDto;

    /**
     * Default constructor to initialize the instance
     */
    public VatCodeDtoBuilder() {
        vatCodeDto = new VatCodeDto();
    }

    public VatCodeDtoBuilder description(String description) {
        vatCodeDto.setDescription(description);
        return this;
    }

    public VatCodeDtoBuilder id(String id) {
        vatCodeDto.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public VatCodeDto build() {
        return vatCodeDto;
    }
}