/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class VatInformationScheduleDtoBuilder {
    //the instance to build
    private VatInformationScheduleDto vatInformationScheduleDto;

    /**
     * Default constructor to initialize the instance
     */
    public VatInformationScheduleDtoBuilder() {
        vatInformationScheduleDto = new VatInformationScheduleDto();
    }

    public VatInformationScheduleDtoBuilder maxTaxableAmt(Double maxTaxableAmt) {
        vatInformationScheduleDto.setMaxTaxableAmt(maxTaxableAmt);
        return this;
    }

    public VatInformationScheduleDtoBuilder minTaxableAmt(Double minTaxableAmt) {
        vatInformationScheduleDto.setMinTaxableAmt(minTaxableAmt);
        return this;
    }

    public VatInformationScheduleDtoBuilder reportingGroup(String reportingGroup) {
        vatInformationScheduleDto.setReportingGroup(reportingGroup);
        return this;
    }

    public VatInformationScheduleDtoBuilder startDate(Date startDate) {
        vatInformationScheduleDto.setStartDate(startDate);
        return this;
    }

    public VatInformationScheduleDtoBuilder vatRate(Double vatRate) {
        vatInformationScheduleDto.setVatRate(vatRate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public VatInformationScheduleDto build() {
        return vatInformationScheduleDto;
    }
}