/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class VatInformationDtoBuilder {
    //the instance to build
    private VatInformationDto vatInformationDto;

    /**
     * Default constructor to initialize the instance
     */
    public VatInformationDtoBuilder() {
        vatInformationDto = new VatInformationDto();
    }

    public VatInformationDtoBuilder calculateOn(CalculateOnEnum calculateOn) {
        vatInformationDto.setCalculateOn(calculateOn);
        return this;
    }

    public VatInformationDtoBuilder cashDiscount(CashDiscountEnum cashDiscount) {
        vatInformationDto.setCashDiscount(cashDiscount);
        return this;
    }

    public VatInformationDtoBuilder categories(List<VatCategoryDto> categories) {
        vatInformationDto.setCategories(categories);
        return this;
    }

    public VatInformationDtoBuilder deductibleVat(Boolean deductibleVat) {
        vatInformationDto.setDeductibleVat(deductibleVat);
        return this;
    }

    public VatInformationDtoBuilder defaultNonStockItem(InventoryNumberDescriptionDto defaultNonStockItem) {
        vatInformationDto.setDefaultNonStockItem(defaultNonStockItem);
        return this;
    }

    public VatInformationDtoBuilder description(String description) {
        vatInformationDto.setDescription(description);
        return this;
    }

    public VatInformationDtoBuilder documentText(DocumentTextEnum documentText) {
        vatInformationDto.setDocumentText(documentText);
        return this;
    }

    public VatInformationDtoBuilder enterFromVatInvoice(Boolean enterFromVatInvoice) {
        vatInformationDto.setEnterFromVatInvoice(enterFromVatInvoice);
        return this;
    }

    public VatInformationDtoBuilder euReportCode(EuReportCodeEnum euReportCode) {
        vatInformationDto.setEuReportCode(euReportCode);
        return this;
    }

    public VatInformationDtoBuilder glAccounts(VatGlAccountsDto glAccounts) {
        vatInformationDto.setGlAccounts(glAccounts);
        return this;
    }

    public VatInformationDtoBuilder includeinVatExemptTotal(Boolean includeinVatExemptTotal) {
        vatInformationDto.setIncludeinVatExemptTotal(includeinVatExemptTotal);
        return this;
    }

    public VatInformationDtoBuilder includeinVatTotal(Boolean includeinVatTotal) {
        vatInformationDto.setIncludeinVatTotal(includeinVatTotal);
        return this;
    }

    public VatInformationDtoBuilder lastModifiedDateTime(Date lastModifiedDateTime) {
        vatInformationDto.setLastModifiedDateTime(lastModifiedDateTime);
        return this;
    }

    public VatInformationDtoBuilder notValidAfter(Date notValidAfter) {
        vatInformationDto.setNotValidAfter(notValidAfter);
        return this;
    }

    public VatInformationDtoBuilder pendingVat(Boolean pendingVat) {
        vatInformationDto.setPendingVat(pendingVat);
        return this;
    }

    public VatInformationDtoBuilder reverseVat(Boolean reverseVat) {
        vatInformationDto.setReverseVat(reverseVat);
        return this;
    }

    public VatInformationDtoBuilder schedules(List<VatInformationScheduleDto> schedules) {
        vatInformationDto.setSchedules(schedules);
        return this;
    }

    public VatInformationDtoBuilder statisticalVat(Boolean statisticalVat) {
        vatInformationDto.setStatisticalVat(statisticalVat);
        return this;
    }

    public VatInformationDtoBuilder type(Type358Enum type) {
        vatInformationDto.setType(type);
        return this;
    }

    public VatInformationDtoBuilder vatAgencyId(SupplierNumberDto vatAgencyId) {
        vatInformationDto.setVatAgencyId(vatAgencyId);
        return this;
    }

    public VatInformationDtoBuilder vatCategoryId(String vatCategoryId) {
        vatInformationDto.setVatCategoryId(vatCategoryId);
        return this;
    }

    public VatInformationDtoBuilder vatId(String vatId) {
        vatInformationDto.setVatId(vatId);
        return this;
    }

    public VatInformationDtoBuilder vismaXmlVatType(VismaXmlVatTypeEnum vismaXmlVatType) {
        vatInformationDto.setVismaXmlVatType(vismaXmlVatType);
        return this;
    }

    public VatInformationDtoBuilder zones(List<VatZoneDto> zones) {
        vatInformationDto.setZones(zones);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public VatInformationDto build() {
        return vatInformationDto;
    }
}