/*
 * VismaNetAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package no.systema.visma.sdk.models;

import java.util.*;

public class WarehouseIdDescriptionDtoBuilder {
    //the instance to build
    private WarehouseIdDescriptionDto warehouseIdDescriptionDto;

    /**
     * Default constructor to initialize the instance
     */
    public WarehouseIdDescriptionDtoBuilder() {
        warehouseIdDescriptionDto = new WarehouseIdDescriptionDto();
    }

    public WarehouseIdDescriptionDtoBuilder description(String description) {
        warehouseIdDescriptionDto.setDescription(description);
        return this;
    }

    public WarehouseIdDescriptionDtoBuilder id(String id) {
        warehouseIdDescriptionDto.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public WarehouseIdDescriptionDto build() {
        return warehouseIdDescriptionDto;
    }
}